### ISSUE TITLE
Panic with some go file

### ISSUE THREAD

**Issue by jerry-tao** [boyter/scc#106]
**Describe the bug**

Run `scc` with this file `https://github.com/360EntSecGroup-Skylar/goreporter/blob/master/engine/template.html.go`, and you will get the panic

```
panic: runtime error: index out of range

goroutine 23 [running]:
github.com/boyter/scc/processor.CountStats(0xc000254000)
```

**To Reproduce**

1. Tell us how you were using `scc` either as command line or library.

Both.

2. If command line please list the arguments. If library please supply code to demonstrate the issue.

3. If the issue is a miscount or some such please link or supply a file which demonstrates the issue.

```
https://github.com/360EntSecGroup-Skylar/goreporter/blob/master/engine/template.html.go
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS:macOS

**Comment by dbaggerman** [comment]
Confirmed.

It looks like start/end quotes aren't being matched properly. It's entering the string state when it sees the `` ` ``, but it's treating the `"` quotes inside as valid end string characters.

We'll need to ensure that strings opened with a `` ` `` are only closed on a `` ` ``.
