### ISSUE TITLE
Include ext option seems to have no effect

### ISSUE THREAD

**Issue by cardil** [boyter/scc#108]
**Describe the bug**
Using a `--include-ext` option seems to have no effect

**To Reproduce**

1. `git clone https://github.com/boyter/scc.git`
2. `scc --include-ext java,md`

**Expected behavior**
Only `*.java` and `*.md` files should be counted and reported but output isn't diffrent then with just `scc`

**Desktop (please complete the following information):**
 - OS: Windows 7 Cygwin
 - Version scc 2.7.0

**Comment by boyter** [comment]
Confirmed. This appears to have crept in with the file walker changes that fix multiple .gitignore options.

**Comment by boyter** [comment]
Quick fix added to master so if you build from source @cardil this should be resolved for you.

Added regression test to ensure this isn't done again. Thanks for reporting it. Ill make a release in the next few days.

**Comment by boyter** [comment]
Latest release should resolve this.
