### ISSUE TITLE
Snap packaging

### ISSUE THREAD

**Issue by cardil** [boyter/scc#110]
Snap packages are the most popular cross platform packaging solution. They support almost all linux distributions. It's also possible to use them on MacOS via homebrew. Microsoft also is considering supporting them as they already package software for linux with snapcraft.

Snaps are automatically updated and easy for users to find. Snaps are containerized so it is ideal for application developers.

Consider publishing scc as snap package!

https://snapcraft.io/ - more info.

https://snapcraft.io/first-snap/golang - a tutorial for package go app as a snap package.

Alternatives, but less popular are AppImage and FlatPack

**Comment by boyter** [comment]
Thankfully this already exists https://snapcraft.io/scc and is being maintained by https://feliciano.tech/ on github https://github.com/felicianotech/snap-scc

Is there some reason this one is not working for you?

**Comment by cardil** [comment]
Oh. I didn't notice that earlier. I'll check that today. 

Maybe a good idea is to make installation section in `README.md` more prominent with clear options of installation with commands.

**Comment by boyter** [comment]
Moved install instructions "above the fold". Now it is just after the licence information.

**Comment by cardil** [comment]
I would advise to introduce easy to see subsections, like:

## Install

There are multiple supported ways to install scc.

### Go

If you are comfortable using Go and have >= 1.10 installed the usual go get will install for you.

```bash
go get -u github.com/boyter/scc/
```

### Snap (GNU/Linux)

A snap package exists https://snapcraft.io/scc thanks to [Ricardo](https://feliciano.tech/). You can run install it with command line or software center. Snap package will be automatically updated to the newest version of scc.

```bash
snap install scc
```

### Binaries

If you are looking for binaries see [Releases](https://github.com/boyter/scc/releases) for Windows, GNU/Linux and macOS for both i386 and x86_64 bit machines.

```bash
curl -L https://github.com/boyter/scc/releases/download/v2.8.0/scc-2.8.0-x86_64-unknown-linux.zip -o scc-2.8.0-x86_64-unknown-linux.zip
unzip scc-2.8.0-x86_64-unknown-linux.zip
sudo install scc -t /usr/local/bin
```

**Comment by boyter** [comment]
@cardil Might be worth submitting a PR for this.

**Comment by carlosame** [comment]
I installed `scc` via snap on Xubuntu 19.04 and does not work. It always gives the same error:

`ERROR 2019-10-05T18:31:51Z: failed to open .: open .: permission denied`

or

`ERROR 2019-10-05T18:36:07Z: failed to open somedir: open somedir: permission denied`

However, when running from a local golang installation instead of the snap, `scc` works fine.

It is the latest snap, version:

```
$ scc --version
scc version 2.8.0
```

**Comment by boyter** [comment]
@carlosame can you raise this as a bug here https://github.com/felicianotech/snap-scc and link back here please?
