### ISSUE TITLE
--no-cocomo is not working sometimes

### ISSUE THREAD

**Issue by anup1920sri** [boyter/scc#111]
**Describe the bug**

**To Reproduce**

1. Tell us how you were using `scc` either as command line or library.
2. If command line please list the arguments. If library please supply code to demonstrate the issue.
3. If the issue is a miscount or some such please link or supply a file which demonstrates the issue.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by boyter** [comment]
Seems to have been cleared up over here https://github.com/boyter/scc/commit/76fc0cac74b334267f175a9a6f4d57cbd3b1ed59

It was down to breaking change made in 2.8.0 where it the option was renamed.

**Comment by anup1920sri** [comment]
Yaa issue is fixed and now in 2.8.0 its working fine. Thanks and appreciate for supporting @boyter

**Comment by boyter** [comment]
All thanks to @elindsey for doing it actually! I try not to do any commits on the weekend so sorry about my lack of response over the the last 48 hours.
