### ISSUE TITLE
Enhancement: Add ability to ignore files based on number of lines or size

### ISSUE THREAD

**Issue by boyter** [boyter/scc#122]
Would be good to help ignore files that are stupidly large. Related to the minified/generated checks.

Turning option on should ignore those files from the output and flag it via verbose output. Needs to also be configurable. 

Per lines and per bytes seems like a good way to achieve this.

**Comment by dbaggerman** [comment]
The number of lines is only known after the file has been processed, which might defeat the purpose of ignoring.

File size is more feasible. You can get that from `os.Stat` before reading the file.

**Comment by boyter** [comment]
The purpose is not performance related. That could be a nice benefit though. 

Its mostly about getting better results out of the run where you know certain things should not be counted.

**Comment by boyter** [comment]
See https://github.com/boyter/scc/issues/92 and comment by jhaynie for details on what look like sensible defaults.
