### ISSUE TITLE
Questions regarding COCOMO and other cost metrics

### ISSUE THREAD

**Issue by DonaldTsang** [boyter/scc#132]
Is COCOMO referring to https://en.wikipedia.org/wiki/COCOMO ? If so the cost would be in USD (in year 2000) according to the wiki article, therefore the number would need to be adjusted to inflation and rate conversion (if it is in a foreign country like Europe or East Asia). `--avg-wage` does work, but what about the badges that don't have this param for localization?

Also is it possible to add in other metrics like the ones in this list for metrics comparison?
- https://en.wikipedia.org/wiki/SEER-SEM
- https://en.wikipedia.org/wiki/COSYSMO
- https://en.wikipedia.org/wiki/Putnam_model
- https://en.wikipedia.org/wiki/MK_II_FPA

**Comment by boyter** [comment]
I believe it is although it might be the COCOMO2 model. It's based on the numbers that sloccount https://dwheeler.com/sloccount/ returns, so for the redis project,

```
Total Estimated Cost to Develop                           = $ 5,256,850
 (average salary = $56,286/year, overhead = 2.40).
```

which `scc` estimates as 

```
Estimated Cost to Develop $5,769,821
```

It was very deliberate to implement the same calculation it does to ensure that I could check that the output was correct.

As you say the wage does need to be adjusted for other countries and inflation. I don't have any idea around how to do this at the moment though. Hence the inclusion of `--avg-wage`. Thoughts?

As for the badges... there is nothing in there to deal with this. Sounds like a reasonable to change to implement though.

As for other models, I don't see why not. Adding them in is not a huge issue as it would just be another flag to switch out the model assuming the inputs are fairly similar. 

I would need to see pseudo-code for them with example inputs and outputs. Given that I will be happy to make this as an enhancement.

**Comment by boyter** [comment]
@DonaldTsang You can not set the avg-wage using the badges, for example,

https://sloc.xyz/github/boyter/scc/?category=cocomo&avg-wage=1
https://sloc.xyz/github/boyter/scc/?category=cocomo&avg-wage=100000

Note it needs to be a positive integer to work. Probably something about a limit to 32 bits integers as well but nobody gets paid that much (unless Zimbabwe or Venezuela and they probably convert to USD or something anyway) so moot point.

**Comment by DonaldTsang** [comment]
@boyter We should be sensible with the ranges, the smallest amount of currency in Europe, East Asia and North America (basically the First World) would be the Korean Won and the Vietnamese Dong. It is understandable that there is a limit to the numbers.

**Comment by boyter** [comment]
Yep there is no limit beyond whatever the integer type in Python 3.7 supports.

**Comment by boyter** [comment]
@DonaldTsang So I had a look at the models in depth. 

COSYSMO appears to be more of a planning algorithm, which takes in input which scc does not have access to. I doubt it can be easily implemented as it would have to prompt the user for input, or take in a guess based on what it has, but I would need to know how to generate those inputs. 

Putnam looks to be the easiest to get going however based on the information that scc has. If you know of an implementation I can compare against that would help a lot. I had a look around but couldn't find anything that I could try. Hoping you have an idea.

As for the others I am not sure if they would work.

Ideally I need the following for each model.

1. An example implementation, which I can put into into and view results to ensure the algorithm is implemented correctly in scc.

2. An example of the algorithm in any programming language, Python would be ideal as its easy to read but I will settle for whatever or even pseudocode.

If you can help with the above that would greatly assist me and I can get another model into the next scc release.

**Comment by boyter** [comment]
Closing down because I don't have enough information to implement this. Would be happy to implement Putnam but due to lack of something to follow...
