### ISSUE TITLE
Open file limit may be reached on top-end Mac Pro

### ISSUE THREAD

**Issue by dbaggerman** [boyter/scc#137]
**Describe the bug**

Making sure we don't lose track of points raised in #134. 

By default, we launch `4 * runtime.NumCPU()` file readers, and `runtime.NumCPU()` directory walkers. This means that we have an upper bound of 5 file handles per CPU thread.

A top end Mac Pro has 28 cores, or 56 threads. This would add up to 280 workers that open file handles, which would exceed the default `ulimit` of 256 on MacOS.

**To Reproduce**

1. Buy a maximum spec Mac Pro with 28 cores.
2. Run `scc`.

**Expected behavior**

Past a certain point, throwing more CPU cores at reading files won't improve disk throughput. We should just make a call that N readers should be enough to saturate the available IOPS (for some value of N) and cap it there. This could be paired with a `--num-readers` flag for more exotic setups with huge disk IOPS which may benefit from more.

The alternative is to try to dynamically query the `ulimit` and scale readers appropriately, but I don't think this can be done in a cross-platform way.

**Comment by boyter** [comment]
I am more in favor of the `ulimit` one if possible. Agree it might not be cross-platform.

I wonder if there is some way to get the IOPS's value from the disk itself, and base it on that though.

**Comment by dbaggerman** [comment]
Benchmarked with file readers and directory walkers set to different values. This is on a quad core (8 thread) laptop which would run 32 readers with the current default.

For me at least, 2 was actually the sweet spot. Adding more past that made it progressively slower, though by a very small margin. That matches with my intuition, that a small handful is optimal and adding more just increases contention.

Personally, I would just set a default of probably 4, unless `runtime.NumCPU()` is lower, and add a `--num-readers` flag for people that want to change it.

```
Benchmark #1: ./scc-1 ../../torvalds/linux
  Time (mean ± σ):      1.876 s ±  0.022 s    [User: 11.811 s, System: 0.911 s]
  Range (min … max):    1.839 s …  1.972 s    100 runs

Benchmark #2: ./scc-2 ../../torvalds/linux
  Time (mean ± σ):      1.757 s ±  0.012 s    [User: 12.580 s, System: 0.970 s]
  Range (min … max):    1.741 s …  1.833 s    100 runs

Benchmark #3: ./scc-4 ../../torvalds/linux
  Time (mean ± σ):      1.769 s ±  0.010 s    [User: 12.673 s, System: 0.983 s]
  Range (min … max):    1.755 s …  1.828 s    100 runs

Benchmark #4: ./scc-8 ../../torvalds/linux
  Time (mean ± σ):      1.773 s ±  0.016 s    [User: 12.725 s, System: 0.993 s]
  Range (min … max):    1.755 s …  1.858 s    100 runs

Benchmark #5: ./scc-16 ../../torvalds/linux
  Time (mean ± σ):      1.781 s ±  0.018 s    [User: 12.775 s, System: 1.007 s]
  Range (min … max):    1.761 s …  1.888 s    100 runs

Benchmark #6: ./scc-32 ../../torvalds/linux
  Time (mean ± σ):      1.791 s ±  0.011 s    [User: 12.857 s, System: 1.029 s]
  Range (min … max):    1.780 s …  1.849 s    100 runs

Benchmark #7: ./scc-64 ../../torvalds/linux
  Time (mean ± σ):      1.794 s ±  0.013 s    [User: 12.870 s, System: 1.032 s]
  Range (min … max):    1.782 s …  1.882 s    100 runs
```

**Comment by dbaggerman** [comment]
> I am more in favor of the ulimit one if possible. Agree it might not be cross-platform.

It's possible, at least on POSIX systems (I don't have a clue how file limits work on Windows). I would be a little concerned what platform specific code means for testing.

> I wonder if there is some way to get the IOPS's value from the disk itself, and base it on that though.

Pretty sure that's impossible. IOPS values themselves can vary depending on usage patterns, for example sequential reads vs random access.

There's also no guarantee that everything we're reading is even on the same disk, or a disk the client has visibility on. Running `scc` on something that's NFS mounted is an obvious example, but on Linux it's also quite common to use block device mappings like LVM that would make it hard to figure out what the underlying disk is.

**Comment by boyter** [comment]
Ill have a look into something for windows. Perhaps it could be ulimit where possible and otherwise a sensible default might be a good approach.

https://github.com/mackerelio/go-osstat#supported-os

As you say seems not possible in some cross platform way. I think its reasonable though if it were possible to just test the endpoint where its running to guess it quickly, but alas.

I guess my ideal would be something that works now well and scales with disk improvements. The catch being we are getting more cores faster than we are getting faster HDD. Might have go spelunking through some other code bases and see how they deal with this. It feels like it should be a solved problem somewhere.

**Comment by boyter** [comment]
BTW if anyone wants to buy both @dbaggerman and I a maximum spec Mac Pro with 28 cores or more please let us know here LOL
