### ISSUE TITLE
Can we use scc as part of larger Python code (via API)

### ISSUE THREAD

**Issue by svenka3** [boyter/scc#138]
Hello,
  Sorry if this is off topic here, but I recently discovered SCC and looks interesting to some of our code audit tools. I am wondering if there is a way to call scc and get information about a source file (Say C file) inside a Python code. I would tend to think that this is common use model, am I off track here?

Thanks
Srini

**Comment by boyter** [comment]
You are correct that's a fairly common way to use it.

Probably the easiest way would be to call out to the scc executable. I do exactly this for the github badges https://github.com/boyter/scc-lambda where I call it and specify JSON output which I read back in and work with.

This assumes the file is on disk however. 

Perhaps you mean you want to pipe the contents into scc itself? Something like `cat myfile.c | scc` or some such? This is not currently supported but perhaps is something to consider.

I would need some more details about what you are actually trying to do here, but even if you had to save the file to a temp location and run scc over that file it should still work for you.

**Comment by boyter** [comment]
No response after four days. Going to assume the suggestions solved the issue.
