### ISSUE TITLE
Add a HTML output formation option

### ISSUE THREAD

**Issue by eric-zheng** [boyter/scc#139]
**Describe the bug**
When I run scc on command line, the report table shows correctly on the command line terminal. But if I pipe the result to a file and open the file with common editor / browser, the line separator of the table is displayed incorrectly. I tried to change the character encoding but couldn't fix the issue.

**To Reproduce**

```bash
.\scc.exe --version
scc version 2.10.1

.\scc.exe > report.txt
.\scc.exe > report.html
```

Then, open the report.txt with code editor and open the report.html with browsers (I used Chrome and Edge). The line separator is encoded as `ΓöÇΓöÇΓöÇΓöÇ`.

**Expected behavior**

I think the line separator of the table is not the common ascii "-" dash character. But I'm not sure how to encode it correctly on browser/editor. It would be good if scc supports to generate a file output with certain extensions (.html, .txt) that display the report table correctly. Thanks!

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Version: 2.10.1

**Comment by boyter** [comment]
Thankfully there is already an option to deal with this.

`scc --ci`

Which will output the format using - and not box lines which should resolve this issue for you. In effect it reduces the output to pure ascii and not unicode.

I suspect based on your name that when you redirect the output you are not specifying the encoding type, and as such it the encoding is incorrect from your terminal to your browser resulting in the symptom.

Can you please try with the `--ci` option which should resolve this in the short term. In the long term if you wish to see box lines you should confirm that your terminal and browser are using the same encoding type.

**Comment by boyter** [comment]
A HTML output option might be worth implementing. Probably just need to output to a simple table with headers. Should make the enclosing of a <html></html> an optional param to turn the output into a self contained format. Could possibly link out to https://www.datatables.net/ to provide a nice interface, but that seems like overkill.

Might be worth looking to see if any of the other tools do this as well.

**Comment by eric-zheng** [comment]
Appreciate that you would like to consider this feature. I will check tomorrow to see if `--ci` works for me. But generally speaking, an HTML option would be helpful. Thanks for making this awesome (fast) tool.

**Comment by boyter** [comment]
Have a PR going with this implemented. Example screenshot of the `html` output (full page)

![image](https://user-images.githubusercontent.com/612151/71789515-8f37cc80-307f-11ea-9963-3858e2bd3108.png)

and there is an option for just the table output if you want to embed into another page.

**Comment by boyter** [comment]
@eric-zheng This is now in master for you. It looks alright to me and is fairly minimal and should be flexible enough for you to use how you want.
