### ISSUE TITLE
Treat all .C and .h files as C++?

### ISSUE THREAD

**Issue by e4lam** [boyter/scc#142]
I have a codebase that has the unusual convention that files with extensions .h and .C are actually compiled as C++. Is there some way to make scc treat these extensions as C++?

**Comment by boyter** [comment]
The only way to do this at the moment would be modify the languages.json then `go generate` and `go build` to do this. 

However the next version of `scc` will have support for this with this https://github.com/boyter/scc/issues/128 enhancement I want to add. If you want to add the functionality yourself and submit a PR that would help, but seeing as I want it its just a matter of waiting.

I will be going off the grid till Jan 2020 so don't expect it before then sorry :)

**Comment by e4lam** [comment]
I'll gladly wait. Nice to know it's in the plans!

**Comment by boyter** [comment]
@e4lam this is now sitting in master. If you build from there you can now override any extension you wish. It will make it into a release in the coming weeks.

**Comment by e4lam** [comment]
@boyter Great, thank you!

**Comment by boyter** [comment]
@e4lam let me know if you run into any issues and ill fix it before the release.

**Comment by e4lam** [comment]
@boyter Ah, I don't normally use Go so I'll just wait for the binary release. To be honest, it was already good enough that I didn't care too much that my C++ sources files were being treated as C++ but I figure I'd log it anyways for the next time I want to do this. :)

**Comment by boyter** [comment]
What OS are you using? I can make a build and put it here for you now.

**Comment by boyter** [comment]
Should do this to ensure you see it ping @e4lam

**Comment by e4lam** [comment]
@boyter Windows

**Comment by boyter** [comment]
Cool. I need to resolve it so it builds on Windows again and then ill drop a new version here for you.

**Comment by e4lam** [comment]
Thank you! I was thoroughly impressed at the speed at which it churned on the multi-million lines of code at work.

**Comment by boyter** [comment]
No problem at all. Glad it impressed you with its speed. Performance is something I tried to pay a lot of attention to when building it and I wanted it to be the fastest code counter that was possible.

Below is a build for you as a zip with hashes included in case you want to confirm the download.

[scc-2.11.0-x86_64-pc-windows.zip](https://github.com/boyter/scc/files/4043957/scc-2.11.0-x86_64-pc-windows.zip)

```
$ hashit scc
scc (4009984 bytes)
        MD5 58ed94f749105bd200697e9706e4d63a
       SHA1 77f62f558e2aef83493a40cf0a98718ae3cdf73a
     SHA256 6b5f2826b7a4a04660f6d1ca644678e35189ee6c41fdfb040c0f4e8aad17380b
     SHA512 9e964ca151df8a8b460123ddf4f07362aa79df31309bf006a0b3553208aa7ec12e35d79f0d62e3c122a28f79389a361c2f3dacce6801be1f8958b556d3204fb9
```

**Comment by e4lam** [comment]
Hmm, I tried running it as:

**Comment by boyter** [comment]
Hmmm so you are saying you want to count all `.h` files as C++ Header and all `.c` as C++? Is that correct?

**Comment by e4lam** [comment]
@boyter Yes, but recall that on Windows (NTFS), filenames are case-preserving but matching is case-insensitive. The files are actually with a `.C` (capital C) extension.

**Comment by e4lam** [comment]
Ah right, using lowercase `c:"C++"` worked.

**Comment by boyter** [comment]
Yeah you just beat me to it. I was about suggest something like

```
scc --count-as h:"C++ Header",c:"C++",C:"C++"
```

which should do it for you.

**Comment by e4lam** [comment]
I still find it strange that `C:"C++` didn't work though because my files are actually using a capital `.C` extension.

**Comment by boyter** [comment]
Ill have a poke around. The main thing right now is that you have a workaround. I should have it 100% correct by the time of release.

**Comment by dbaggerman** [comment]
It's because we implement case-insensitive matching by lower-casing the file extension before looking up the language. Technically, `C:"C++"` will currently never match anything since `filename.C` will get lower-cased to a `.c` extension lookup.

Maybe we should lower-case the extension that we're remapping too, to match the extension matching behaviour.

**Comment by e4lam** [comment]
Ok, I think that makes sense to do if you're already doing that with the
filename extensions. Although you might consider an option to do
case-sensitive matching in the future? The ancient codebase that I use
actually had a lowercase .c for C files and uppercase .C for C++ files back
when it was on Unix only.

Regardless, thanks again for adding the feature!

**Comment by boyter** [comment]
Thanks @dbaggerman that is indeed the reason. I will update the code to reflect this.

As for case sensitive matching... I think that could happen in the future. Would probably be an opt-in feature though and needs some thought for cases such as `Java` `java` `jAva` `jAvA` and such.

**Comment by boyter** [comment]
[scc-2.11.0-x86_64-pc-windows.zip](https://github.com/boyter/scc/files/4051525/scc-2.11.0-x86_64-pc-windows.zip)

@e4lam here is another version for you which should resolve any case issues. It just converts everything to lower to match the internal rules.

```
$ hashit scc.exe
scc.exe (4715520 bytes)
        MD5 28a60fa4974a752029876a6686c52ca6
       SHA1 aa09e27cbf4d7716dce61096ad3977f85d5b880e
     SHA256 7b18f118fac5ad1359e8bec86f43723a51688e7e0da56283e62f682a6e0ea976
     SHA512 541b6fb27e94543a3ad40a8da3827aa9979f9dd86160c32e87fa0dd5e171173d5a30b26110e696c20d14b5d0b81a1abef2fc96e3c694a2f8ee361ecf44c813cb

$ hashit scc-2.11.0-x86_64-pc-windows.zip
scc-2.11.0-x86_64-pc-windows.zip (1776870 bytes)
        MD5 d9260cdb75e1c30a0fd51710f34dcc73
       SHA1 d3c5694cfca8eaf5c1eb7a52f8fbb4f79c104770
     SHA256 2b62575396924d162b79fd08e193fc7f2cbf6873d3bebbf3b812acf9caf75799
     SHA512 83f6fcd12feb3d77abacdbc247fea6c42c618ff8a36641c729e249d0e995d992d3d8ae80f783c3efe68e7d70bab777d4aa771e06c2c7a147c5a63493bd601f16
```

**Comment by e4lam** [comment]
@boyter Sorry, I had meant to get back to this earlier but never got around to it until now. Just tried it again and my use case now works as expected (of course). Thanks, again!

**Comment by boyter** [comment]
Great to hear @e4lam
