### ISSUE TITLE
Submit to AUR

### ISSUE THREAD

**Issue by boyter** [boyter/scc#145]
Submit to AUR

https://github.com/boyter/scc/pull/144

**Comment by ilai-deutel** [comment]
Hi! I just saw this and I could use a `scc` ArchLinux package, so I can take care of this if nobody else is on it.

According to the [AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines), package `scc` should build from source. If building is too slow and a binary release (like the one used in the [PKGBUILD](https://github.com/boyter/scc/blob/master/packages/aur/PKGBUILD)) is preferred, it must be called `scc-bin` (we can also have both).

Do you want to keep the PKGBUILDs in the repo? It means having to keep this repo and the AUR repo in sync, and update the PKGBUILDs in repo for each release. I don't think it is common to keep the PKGBUILDs in upstream repos, but if you prefer, it's fine! Another solution involves git submodules or git subtrees, but it can be a pain to update them every time.

**Comment by boyter** [comment]
Would be very happy to have someone take this over for me. 

I have no real preference beyond whatever is easier to maintain really.

**Comment by dbaggerman** [comment]
I've been meaning to look into doing it. Given that I use Archlinux, it seems appropriate.

**Comment by dbaggerman** [comment]
@ilai-deutel - https://aur.archlinux.org/packages/scc-bin

**Comment by ilai-deutel** [comment]
@dbaggerman Awesome. Just a small comment, you need to `install -Dm 644` the `LICENSE` to `$pkgdir/usr/share/licenses/$pkgname/LICENSE`, because of the custom copyright line in the MIT license (see https://wiki.archlinux.org/index.php/PKGBUILD#license).

I just created the  [`scc`](https://aur.archlinux.org/packages/scc/) package in addition to `scc-bin`

**Comment by boyter** [comment]
Well this looks to be done then.
