### ISSUE TITLE
F# complexity calculation (match)

### ISSUE THREAD

**Issue by kspeakman** [boyter/scc#156]
F# match statements may not be counted in complexity calculation. The language.json file has "switch" listed probably where "match" should be. F# has no "switch" keyword.

```fsharp
match someBool with
| true -> "yah"
| false -> "nope"
```

Similarly, Elm complexity has "switch" where "case" probably should be.

```elm
case someBool of
    True ->
        "yah"

    False ->
        "nope"
```

**Comment by boyter** [comment]
Pretty simple fix. Applied on master. If you are able to build from that it should work for you, otherwise it will get pushed into the next release.

**Comment by kspeakman** [comment]
Thanks!

**Comment by boyter** [comment]
No worries at all.
