### ISSUE TITLE
Cannot sort by file name

### ISSUE THREAD

**Issue by John-Wilcox** [boyter/scc#158]
When using the command 
`scc  --by-file --sort name`  OR
`scc  --by-file --sort files` OR
`scc  --by-file `

The output is always sorted by lines

**Comment by boyter** [comment]
Wow that's am embarrassing gaff. I always new the lack of tests around formatting would bite me. 

Thanks for raising it. Fixing now.

**Comment by boyter** [comment]
Should be a fix in master to resolve this. 

Note that the sort is based on the location and uses usual rules so you get results like the below

```
Java                        23      3912      798       651     2463        547
───────────────────────────────────────────────────────────────────────────────
~es/complexity/complexity.java         5        0         0        5          1
examples/duplicates/1.java           186       38        31      117         26
examples/duplicates/10.java          186       38        31      117         26
examples/duplicates/11.java          186       38        31      117         26
examples/duplicates/12.java          186       38        31      117         26
```

Where 1.java is above 10.java but that's the same as any filesystem sort anyway.

**Comment by John-Wilcox** [comment]
Great project. Glad to be able to contribute.

**Comment by boyter** [comment]
Thanks for saying so. These sort of things really help with the motivation.
