### ISSUE TITLE
Split line longer than one line

### ISSUE THREAD

**Issue by prehistoric-penguin** [boyter/scc#163]
**Describe the bug**
Split line longer than one line, which seems strange
![Imgur](https://i.imgur.com/MwolydS.png)

**To Reproduce**

1. Set large font terminal size on Ubuntu 19.10 (font type Consolas regular, size 18, scaling factor 1.0)
2. Run command `scc flatbuffers/src`

**Expected behavior**

The split line won't be longer than one line width, which will be nicer to look

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [19.10]

Scc version: 2.12.0

**Comment by boyter** [comment]
Now that is interesting. The box lines drawn should not be drawn differently, but apparently this is not the case in some situations.

@prehistoric-penguin Are you able to try running with the `--ci` flag to ensure that it is just the box lines?

**Comment by prehistoric-penguin** [comment]
I am repairing my PC, I will report a few days latter.

**Comment by prehistoric-penguin** [comment]
When running with `--ci` the output looks fine, so the error is locale related? 

My locale:
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

**Comment by prehistoric-penguin** [comment]
I find the reason:

In gnome-terminal, there is one configuration:
**Ambiguous-width characters**
I have set it to wide when resetting it to narrow, the problem is gone.

**Comment by boyter** [comment]
Thank goodness for that! Was getting worried there. Glad its resolved for you.
