### ISSUE TITLE
gocyclo and golint

### ISSUE THREAD

**Issue by hugolgst** [boyter/scc#168]
You should resolve gocyclo and golint issues.

https://goreportcard.com/report/github.com/boyter/scc

**Comment by boyter** [comment]
Lint for sure... however gocyclo is probably not going to happen. The main reason for this is performance. I did look at trying to resolve a lot of the things it raises but at the time it resulted in performance regressions which is not in the spirit of the tool.

**Comment by boyter** [comment]
Done. Thanks for reporting on it.

**Comment by hugolgst** [comment]
Great!
Keep going, a great piece of software here!

**Comment by boyter** [comment]
Glad to hear that.
