### ISSUE TITLE
move to go modules

### ISSUE THREAD

**Issue by 5paceToast** [boyter/scc#169]
**Describe the bug**
You cannot clone the repository and run `go build .` outside of GOPATH.

**To Reproduce**
1. git clone https://github.com/boyter/scc.git
2. cd scc
3. go build .

**Expected behavior**
SCC builds.

**Desktop (please complete the following information):**
Arch Linux

**Recommended approach:**
1. run `go mod init github.com/boyter/scc` - this will parse the current system (gopkg) and replicate
2. regenerate vendor directory (or remove vendoring)

**Comment by boyter** [comment]
I guess `go modules` are mature enough now to try it out.

**Comment by 5paceToast** [comment]
They're actually fully released as of go 1.14.
To quote the [release blog post](https://blog.golang.org/go1.14):
> Module support in the go command is now ready for production use. We encourage all users to migrate to go modules for dependency management.

I've been using them since introduction and haven't had any issues though.

**Comment by boyter** [comment]
I ran into a lot of issues when I first tried it. I did not it was prod ready in 1.14 and thought I should give it another go. Will try it again soon.

**Comment by boyter** [comment]
Graciously done by @dbaggerman
