### ISSUE TITLE
Please add .csx extension for C#

### ISSUE THREAD

**Issue by batkiz** [boyter/scc#174]
`.csx` ext is used by [dotnet script](https://github.com/filipw/dotnet-script) for C# scripting.

**Comment by boyter** [comment]
Yep no worries. Pretty simple to do.

Do you think it should be under its own label though? Rather than just being counted as C#?

Got an example file I could have a look at?

**Comment by batkiz** [comment]
It could be just counted as C#, because GitHub counts it as C# too.

[here](https://github.com/batkiz/CodewarsSolutions/tree/master/csharp) and [here](https://github.com/filipw/dotnet-script/tree/master/build) are some csx files.

And below is GitHub's language details for [my repo](https://github.com/batkiz/CodewarsSolutions), we could see that GitHub counts csx files as C# files.

![image](https://user-images.githubusercontent.com/21122253/82617391-87c62980-9c02-11ea-8ad7-5d8af0009964.png)

**Comment by boyter** [comment]
Yeah linguist has a lot of issues IMHO (thats what github uses) hence I tend to not follow what it does all of the time.

As you say though its just C# so lumping it in there seems fine by me. Ill see about getting it done soonish.

**Comment by boyter** [comment]
Done @batkiz so if you install from latest master it should be in there for you. When I roll out the next release it will be included.

**Comment by batkiz** [comment]
Okay👌
