### ISSUE TITLE
gitignore's double asterisk pattern is not supported

### ISSUE THREAD

**Issue by nnorma** [boyter/scc#178]
**Describe the bug**
`scc` includes files that have been excluded from a repo using `gitignore`'s [double asterisk pattern](https://git-scm.com/docs/gitignore).

**To Reproduce**

1. Install   by running `go get -u github.com/boyter/scc/`
2. Clone [this repo](https://github.com/nnorma/scc-gitignore-bug-asterisk)
3. In the `.gitignore` file, enable each pattern for the `ign` folder in turn and run `scc .` in the root of the repo.  
    - The ignored files specified by double asterisks pattern are not excluded  (lines 7-16).
    - Ignored files are correctly excluded only when there is no double asterisk (line 2)

**Expected behavior**
`scc` should ignore all files specified in the `.gitignore` file. 

For example lines 2 and 7 are equivalent patterns.
Running `scc .` with  only line 2 enabled gives:
```
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
Go                           2        22        6         0       16          0
gitignore                    1        16        5        10        1          0
───────────────────────────────────────────────────────────────────────────────
Total                        3        38       11        10       17          0
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop $374
Estimated Schedule Effort 0.765325 months
Estimated People Required 0.057980
───────────────────────────────────────────────────────────────────────────────
```
and with only line 7 enabled gives:
```
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
Go                           2        22        6         0       16          0
HTML                         1         8        0         0        8          0
Plain Text                   1         8        0         0        8          0
XML                          1         8        0         0        8          0
YAML                         1         8        0         0        8          0
gitignore                    1        16        5        10        1          0
───────────────────────────────────────────────────────────────────────────────
Total                        7        70       11        10       49          0
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop $1,138
Estimated Schedule Effort 1.167576 months
Estimated People Required 0.115497
───────────────────────────────────────────────────────────────────────────────
```
I expect that enabling line 7 should give the same result as enabling line 2.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: 1803
 - SCC version: 2.12.0

**Comment by boyter** [comment]
Not that surprising. Relates somewhat to https://github.com/boyter/scc/issues/150

Do you know where the spec for gitignores actually is? Its one of those things I guess I will have to do myself since I cannot find a decent implementation.

**Comment by nnorma** [comment]
I am going off the [docs for .gitignore](https://git-scm.com/docs/gitignore). Fair enough library you are using does not support this

**Comment by boyter** [comment]
That looks reasonable for me. Ill have a look to implementing something that can process them all.

**Comment by boyter** [comment]
https://github.com/boyter/scc/issues/215
https://github.com/boyter/scc/issues/178 
https://github.com/boyter/scc/issues/150

Going to push out to new release because this needs to be resolved in one large push.

**Comment by viblo** [comment]
I was also hit by this issue. Unless you plan to fix this quickly maybe you could add a note to the Readme about ** not supported? I tested quite a bit to understand if I wrote the pattern correctly or not (should it be / or \, should it be with or without ** etc) before looking here.

**Comment by boyter** [comment]
Its in the next release which is all about .gitignore support. No ETA but yes I am starting to read up on how the patterns work and look to implement against it.

**Comment by boyter** [comment]
I should mention this will include work with the new io/fs package hence waiting so long. Just need to ensure that performance is similar while doing it.

**Comment by boyter** [comment]
This https://github.com/zabawaba99/go-gitignore appears to fulfil all of the requirements. Looking to build out a test suite for this to catch the error as it is now, with all the other checks and then evaluate it.

Most impressive is that its easy to follow compared to the current implementation.

**Comment by boyter** [comment]
@nnorma or @viblo there is a potential fix on branch issue178 https://github.com/boyter/scc/tree/issue178 which as far as I can tell resolves this issue.

It still needs a lot of testing to be dropped back in and some other tweaks but its promising to me. Would love to get feedback from either of you as to how it performs for you.

If you need I can supply a binary here if that helps.

**Comment by viblo** [comment]
Tried it now, but get no change?
I did 
> cd path-to-scc
> git checkout issue178
> go run main.go
And does not get any change in the output regardless what I put in the `.ignore` file? Maybe Im using it wrong?

After various tests my .ignore looks like this:
```
vendor/github.com/**
vendor/golang.org/**
vendor/gopkg.in/**
ignorefile.txt

examples/**
packages/**
processor/**
scripts/**
vendor/**
```
from this I would expect very few lines of code in the result :)

**Comment by boyter** [comment]
Yeah looks like it is not working as I would expect.

While I really didn't want to implement the spec myself looks like it might be the only option.

**Comment by boyter** [comment]
Should be done with the latest change in master.
