### ISSUE TITLE
Pascal comments are counted incorrectly

### ISSUE THREAD

**Issue by LoadEffectiveAddress** [boyter/scc#182]
**Describe the bug**
Pascal comment counting is reporting a much higher comment count than expected when counting our Delphi code.  It appears the `{comment}` style of comment does not "end".  Upon further testing, it appears the unusual nature of Pascal multi-line comments in language.json is to blame - mismatched comment delimiters like `(* comment }` exit correctly, while matched ones (the first two in the list) do not.  After removing the mismatched pairs from the list and regenerating/rebuilding, I can create an executable that counts the matched comments correctly.  I do not know enough about Go to write a fix that works with all sets of delimiters.

**To Reproduce**
This is a simple file that is not really correct Pascal, but currently counts as only 2 lines of code and 11 comments.  The example can be simpler, but I included a second comment to see if it would be considered to close the comment section and treat the second procedure as code.
```
uses
    someunit;

{This is a comment}
procedure Something
var
    avar: String;
begin
    Println('Oho');
end;
{This is a comment}
procedure Nothing
begin
end.
```
**Expected behavior**
The count should 2 comments, 11 lines of code and 1 blank

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10, 1909

**Comment by boyter** [comment]
Interesting... should be hopefully easy to resolve given the test case you have provided here.

**Comment by LoadEffectiveAddress** [comment]
Just in case you feel like it, Pascal did not support single line `//` comments, but Delphi does :)

**Comment by boyter** [comment]
Oh wonderful... that makes it a bit more interesting...

**Comment by LoadEffectiveAddress** [comment]
It should be fine just to treat `//` lines as comments (just like `/* */` vs `//` in C++).  I don't believe `//` has any valid meaning in Pascal that would misidentify a code line as a comment.

Also, I cannot find any evidence that anyone expected to mismatch comment delimiters in Pascal, except in Vim's syntax highlighting, which is probably just a limitation with having two different comment styles.  Neither Delphi nor Lazarus allow `*)` to close a comment started with `{`.  So perhaps eliminating the mismatched pairs in the language file is good enough?

**Comment by boyter** [comment]
Yep that seems like it might be the case. Ill be having a look at this probably today.

**Comment by boyter** [comment]
Should be resolved if you pull from master and build, and will make it into the next release.

**Comment by LoadEffectiveAddress** [comment]
Confirmed with master, thank you (for this fix, and for a blazing fast counter)!

**Comment by boyter** [comment]
Thank you for the excellent bug report!
