### ISSUE TITLE
Tally Size Only for Binary Code (compiled binaries)

### ISSUE THREAD

**Issue by DarwinJS** [boyter/scc#187]
This is along the same lines of estimating scanning costs for security tooling.

Some security tooling scans binaries - the benefits being scanning the final product in its final state and the company submitting the scan data to a cloud vendor does not need to send their plaintext intellectual property to another company.

It's not **source** code counting - but rather is **compiled binary** code counting.

Implementation could be very simple by taking an extensions list **-binariesexttotally "dll,exe"**

There may be intermediary formats that aren't technically source and aren't easy to identify as a binary file on disk - but can be security scanned - so I personally would think a requirement to explicitly identify each file type gives full flexibility in definition and keeps the internal code simple.

**Comment by boyter** [comment]
So by default `scc` will try to identify binary files and ignore them. It does work on the LLVM IR code however.

I would mostly be opposed to counting binaries, as it goes against what the tool is designed to do which is work on source code. I suspect that you aren't going to get anything useful from `scc` counting the binaries that you wouldn't get out of `du`.
