### ISSUE TITLE
Feature Request: Extend custom COCOMO parameters

### ISSUE THREAD

**Issue by michaelcordero** [boyter/scc#188]
--avg-wage is an existing parameter that can be customized, but what about --num-of-devs? Right now the default is 3, how do we change that?

**Comment by boyter** [comment]
So I set it by default to be the same as `sloccount` mainly so I had something to base the calculation off. I am not very familiar with how the calculation is done, but I think you want to be able to change the 0.38 value in this?

https://github.com/boyter/scc/blob/master/processor/cocomo.go

If you can tell me what values you are looking to change (and why) i'll be happy to add them as arguments.

**Comment by michaelcordero** [comment]
@boyter Ok, so after reviewing the original COCOMO model, and researching the COCOMOII model. I realized that number of developers is not an input to the formula, but an output. So this question is sort of malformed, sorry. Generally speaking, **whatever the inputs are, is the desire of this feature request.** So two questions remain to be answered:

1. Are you really using COCOMO II? In your code:

`// EstimateEffort calculate the effort applied using generic COCOMO2 weighted values
func EstimateEffort(sloc int64) float64 {
	var eaf float64 = 1

	// Numbers based on organic project, small team, good experience working with requirements
	var effortApplied = float64(3.2) * math.Pow(float64(sloc)/1000, 1.05) * eaf
	return effortApplied
}`
Please feel free correct me if I'm wrong, but this looks like the COCOMO I formula... E=a(KLOC)^b

2. If you are indeed using COCOMO II, then the inputs increase drastically! 
[COCOMOII](http://softwarecost.org/tools/COCOMO/)

**Comment by boyter** [comment]
It's probably a mistake on my part. Certainly looks more like COCOMO I to me. I vaguely remember trying to find COCOMO II and I think thats what I was trying to implement but I could never find an example in code for me to copy. 

Ill update the COCOMO references for the moment, but if someone finds COCOMO 2 id be happy to add that as well.

**Comment by boyter** [comment]
Updated the comment to avoid future confusion. Also this slightly relates to https://github.com/boyter/scc/issues/132 where other models were mentioned, but I never got an implementation I could follow so nothing happened.

**Comment by adam-moss** [comment]
There is a couple of pdfs in here https://cssedr.usc.edu:4443/csse-tools/cocomo2-javaapplication that explain the COCOMO2 formula I think

**Comment by boyter** [comment]
https://cssedr.usc.edu:4443/csse-tools/cocomo2-javaapplication/cocomo-2000.4.j2/-/blob/master/COCOMO_Manual.pdf

indeed looks pretty solid.

**Comment by boyter** [comment]
I might move this out to the next release. Just so many moving parts in this currently and I really want to get that other one pushed out.

**Comment by boyter** [comment]
Something to do as well is ensure this is moved out in such a way to make it possible to call from 3rd party code.

**Comment by boyter** [comment]
This is now sitting in master. You can use the following params,

```
scc --cocomo-project-type organic
scc --cocomo-project-type semi-detached
scc --cocomo-project-type embedded
```

which will change to calculation between the basic COCOMO types. However you can also supply your own values

```
scc --cocomo-project-type custom,1,1,1,1
```

Allowing you to tweak to whatever suits your project best.

Between this an the existing `--avg-wage` that's about all I can do with the current implementation. I will keep looking into other estimation types in the future but this should give enough flexibility for now.
