### ISSUE TITLE
homebrew support

### ISSUE THREAD

**Issue by ghost** [boyter/scc#19]
a [homebrew](https://brew.sh) formula would be nice

I like the tool a lot so far ! thanks

**Comment by boyter** [comment]
Oh that would be cool. I must confess I don't use a Mac anymore so it would be hard for me to test this. If you are able to supply one I would be happy to maintain it going forward, but I cannot easily create one myself. 

If I have an attempt to create one would you be available to test it @monouser7dig ?

**Comment by monouser7dig** [comment]
I must say I find the homebrew syntax extremely mind boggling and do not understand much of its internals if any.

But I can certainly test it and the maintainers are helpful in general as well.
https://github.com/Homebrew/homebrew-cask/pull/39149 I once submitted a gui (they call it `cask` formula and it worked somewhat well)

**Comment by boyter** [comment]
Okies ill have a look then. I think it should be reasonably straight forward. No idea the process to get it added into their store.

**Comment by monouser7dig** [comment]
I had to make a minor change adding a `v` before the first `#{version}` and the casing of `Bin` seemed to be an issue. Furthermore there is no scc formula yet so you can name it like that I think.

```bash
> brew install sccbin
Warning: sccbin: No available formula with the name "scc" 
'conflicts_with "scc"' should be removed from sccbin.rb.
Please report this to the homebrew/core tap!
==> Downloading https://github.com/boyter/scc/releases/download/v1.4.0/scc-1.4.0-x86_64-apple-darwin.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/12.....
######################################################################## 100.0%
🍺  /usr/local/Cellar/sccbin/1.4.0: 3 files, 4.7MB, built in 5 seconds
```

```ruby
class SccBin < Formula
  version '1.4.0'
  desc "For counting physical the lines of code, blank lines, comment lines, and physical lines of source code in many programming languages."
  homepage "https://github.com/boyter/scc/"

  if OS.mac?
      url "https://github.com/boyter/scc/releases/download/v#{version}/scc-#{version}-x86_64-apple-darwin.zip"
      sha256 "ddb892dc3a0b395de5cdd57015e9ac64b03983cf0c9437134e235d3631a993b2"
  elsif OS.linux?
      url "https://github.com/boyter/scc/releases/download/v#{version}/scc-#{version}-x86_64-unknown-linux.zip"
      sha256 "248a3593cc1f746374017e22eb555701c97844049c951fe966a65f102c99f350"
  end

  conflicts_with "scc"

  def install
    bin.install "scc"
  end
end

```

if you want to support HEAD install you may look at 
https://github.com/Homebrew/homebrew-core/blob/master/Formula/fzf.rb

**Comment by boyter** [comment]
I am pretty comfortable with updating it manually as releases come out. Id prefer something simpler to update.

Well looks like that worked. I will remove the `conflicts_with` portion then and it looks good. Ill do some reading up on how to actually get this added then.

**Comment by monouser7dig** [comment]
Nice, thanks !

**Comment by jpoehls** [comment]
You may want to look into [GoReleaser](https://goreleaser.com/). This automates the process of building and publishing releases and, I think, is used by Hugo among others.

**Comment by boyter** [comment]
@jpoehls Oh that looks cool. Investigating now.

**Comment by jhaynie** [comment]
👍 we use goreleaser and it's easy to setup and you get a bunch of release stuff "for free"

**Comment by elindsey** [comment]
https://github.com/Homebrew/homebrew-core/pull/43347

**Comment by boyter** [comment]
Woah neat @elindsey thanks for sorting that out. The lack of Mac made this almost impossible for me.

**Comment by elindsey** [comment]
I think brew runs on WSL now, but I’m not sure how comparable that is to a Mac installation (for go projects I’d hope it’d be quite similar). In any case, I’ll try to keep up with releases. 🙂 

I’ll send you a PR updating the readme once the brew change is actually merged.

**Comment by boyter** [comment]
I did see that brew works on WSL. Never bothered to try setting it up though. Might give it a go with the new WSL2 when it comes out.

**Comment by elindsey** [comment]
The new formula was finally merged (https://github.com/Homebrew/homebrew-core/pull/43347), so this can be closed. Also just sent them a pr for the 2.8 bump (https://github.com/Homebrew/homebrew-core/pull/44272).

**Comment by boyter** [comment]
Neat! Very cool. Thanks so much for putting the effort into this.
