### ISSUE TITLE
Add support for MQL4 and MQL5

### ISSUE THREAD

**Issue by kenorb** [boyter/scc#2]
- [MQL4](https://github.com/trending/mql4): `.mq4`
- [MQL5](https://github.com/trending/mql5): `.mq5`
- MQL Header files: `.mqh`

Currently it's detected as a plain text.

Related:
- https://github.com/mqsoft/MQL5-sublime

**Comment by boyter** [comment]
Would you be able to fill in the rest of the below JSON structure and then I can add it. You will need to create 3, one for MQL4, MQL5 and MQL Header Files.

In here is fine, unless you want to submit a pull request and get the glory :)

```
"MQL4": {
    "line_comment": [
    ],
    "complexitychecks": [
    ],
    "extensions": [
      "mq4"
    ],
    "multi_line": [],
    "quotes": [
    ]
  },
```

For reference here is simplified Java one. You can find more examples here https://github.com/boyter/scc/blob/master/languages.json

```
"Java": {
  "line_comment": [
    "//"
  ],
  "complexitychecks": [
    "for ",
    "for(",
  ],
  "extensions": [
    "java"
  ],
  "multi_line": [
    [
      "/*",
      "*/"
    ]
  ],
  "quotes": [
    [
      "\"",
      "\""
    ]
  ]
}
```

**Comment by boyter** [comment]
Had a look. Looked easy enough to just copy C++

Added in https://github.com/boyter/scc/pull/13
