### ISSUE TITLE
Provide streaming mode

### ISSUE THREAD

**Issue by alexey-milovidov** [boyter/scc#210]
**Describe the bug**

I cannot successfully run `scc` on 20 TB dump of GitHub (231 219 569 files) without OOM on a server with 128 GiB RAM,
even if I run scc with csv output format.

**Comment by alexey-milovidov** [comment]
This is needed for https://github.com/ClickHouse/ClickHouse/issues/15323

**Comment by boyter** [comment]
Oh that's an interesting one... not one I ever considered, since I have never tried running it over that much data in one go.

I guess a stream option for CSV and SQL works in this case well enough.

**Comment by boyter** [comment]
@alexey-milovidov if you are able to build from source you can get from master and try the new stream mode for csv

```
scc --format csv-stream
```

It should dump the results as they come in to standard output avoiding any memory issues (in theory).

**Comment by boyter** [comment]
Closing down as done and ready for release.
