### ISSUE TITLE
Python Code Counts Innacurate

### ISSUE THREAD

**Issue by abbourne** [boyter/scc#226]
**Describe the bug**
scc counts Python docstrings as code. This can give a very inaccurate view of Python line counts.
(I tried both sloccount  and cloc  on the same code, and they don't have this issue. 

**To Reproduce**
For example:

```
def get_files(dir='.', type=''):
    """get_files is a generator which returns pathlib.Path's of all files of a
    given filetype under a given root directory, traversing sub-directories.
    Args:
        dir (str|Path, optional): A path to a directory to traverse. It can be a
            str or a Path. It efaults to '.', the current directory
        type (str, optional): The filetype of files to select. Defaults to '',
            (all files).
    Returns:
        (pathlib.Path): yields Paths of all files found
    """
    # TODO: Need to add error handling.
    CWD = Path.cwd()
    root = Path(dir)
    for fp in root.glob('**/*' + type):
        yield(CWD.joinpath(fp))
```

scc will count one comment line, the block comment
but it should also count all the docstring lines (between the two """ lines) as comment lines. But scc counts it as code.

**Comment by boyter** [comment]
Odd. Pretty sure this was resolved back here https://github.com/boyter/scc/issues/62 with some conversation about the issue and why it happens plus solution.

I suspect this is because you have `"""get_files` without there being a newline between them though. Something to investigate anyway.

**Comment by abbourne** [comment]
Apologies... I did look through existing issues for existing reports, but I totally missed #62 It explains things very well.
I did try using newline after the """, but that didn't make any difference. But I'll test some more based on the information in #62

**Comment by boyter** [comment]
No worries at all. Its a hard one to find :)

Ill probably look into this a bit more anyway as its one of those things I want to improve.
