### ISSUE TITLE
Not clear in documentation how pathblacklist works

### ISSUE THREAD

**Issue by Zenimax-DSpeed** [boyter/scc#23]
https://github.com/boyter/scc/blob/012df08251362f990130612dbf02249bfb1e3915/processor/file.go#L87

No mention I noticed from the example that it includes the root, and not clear why you might want to potentially blacklist files outside the root?

**Comment by boyter** [comment]
Open and closed instantly. Its a good point though. I think that the blacklist should not apply out of the root.

Any reason for closing this so quickly? I think its a good thing to include.

**Comment by montanaflynn** [comment]
I also can't figure out how to blacklist nested vendor directories. This is important for a go directory containing many packages with their own vendor directories.

**Comment by boyter** [comment]
Odd @montanaflynn because if you say do the following running against `scc` itself.

```
$ scc -co --pbl .git -wl go .
-------------------------------------------------------------------------------
Language                 Files     Lines     Code  Comments   Blanks Complexity
-------------------------------------------------------------------------------
Go                          70      9376     6670      1382     1324       1649
-------------------------------------------------------------------------------
Total                       70      9376     6670      1382     1324       1649
-------------------------------------------------------------------------------

$ scc -co --pbl .git,vendor -wl go .
-------------------------------------------------------------------------------
Language                 Files     Lines     Code  Comments   Blanks Complexity
-------------------------------------------------------------------------------
Go                          28      3517     2684       266      567        635
-------------------------------------------------------------------------------
Total                       28      3517     2684       266      567        635
-------------------------------------------------------------------------------
```

It will exclude the root vendor directory, and as such not even walk what is inside it. Hence any nested ones will also be missed.

I am suspecting perhaps this is not the behavior you are expecting? Could you supply a `tree` output showing me which directories you are expecting to be checked based on your command?

**Comment by montanaflynn** [comment]
I was referring to nested vendor directories @boyter, here's a tree:

```
.
├── packagea
│   ├── packagea.go
│   └── vendor
├── packageb
│   ├── packageb.go
│   └── vendor
```

I want to count `packagea.go` and `packageb.go` but nothing in any vendor directories. Basically I want to use `scc` on a path like `$GOPATH/src/github.com/montanaflynn/` without any vendor directories.

**Comment by boyter** [comment]
Ah fair point. The blacklist is literally just based on the root. 

I should probably add a new option that allows nested folders to be excluded. `--nbl` perhaps. Then keep this existing functionality.

**Comment by mcanfield** [comment]
@boyter in modern javascript/typescript land it is very common to include `.spec.js | .test.js | .spec.ts | .test.ts` right next to their corresponding source code files. Any suggestions on how to filter those files out since the blacklist flag is path not file oriented?

**Comment by boyter** [comment]
Currently there is none. I am thinking perhaps a regex exclusion that you can use to exclude matching folders or files might be the best approach to take here. 

It would allow deprecation of the `--bl` flag as well.

**Comment by boyter** [comment]
@montanaflynn @mcanfield I belive that the above would solve the issue for you. Let me know if you disagree and we can revisit this.

**Comment by montanaflynn** [comment]
@boyter thanks, I verified it would solve the issue for me.

```
 ~/D/g/s/g/b/scc  ⎇ Issue23  mkdir something                                                                                                                                  
 ~/D/g/s/g/b/scc  ⎇ Issue23  mkdir something/vendor                                                                                                                           
 ~/D/g/s/g/b/scc  ⎇ Issue23  touch something/vendor/main.go                                                                                                                   
 go run main.go -v -e "vendor" -co .                                                               
 WARN 2018-09-28T07:31:41Z: skipping directory due to being in blacklist: .git
 WARN 2018-09-28T07:31:41Z: skipping file unknown extension: Gopkg.lock
 WARN 2018-09-28T07:31:41Z: skipping directory due to match exclude: examples
 WARN 2018-09-28T07:31:41Z: skipping file due to match exclude: languages.json
 WARN 2018-09-28T07:31:41Z: skipping directory due to match exclude: scripts
 WARN 2018-09-28T07:31:41Z: skipping directory due to match exclude: vendor
 WARN 2018-09-28T07:31:41Z: skipping directory due to match exclude: vendor
 WARN 2018-09-28T07:31:41Z: skipping directory due to match exclude: cocomo.go
...
```


One thing I might change is listing the relative directory path in the verbose logging so you don't see just the last exluded directory name like:

```
 WARN 2018-09-28T07:31:41Z: skipping directory due to match exclude: vendor
 WARN 2018-09-28T07:31:41Z: skipping directory due to match exclude: vendor
```

**Comment by mcanfield** [comment]
@boyter Heya, yup I just gave it a try and the regex filter works great!  :tada: 

This tool has now become a favorite :). Thank you much!

**Comment by boyter** [comment]
Going to close this on the basis both @mcanfield and @montanaflynn indicate that this resolves their issues.
