### ISSUE TITLE
`go get` won't install the latest version of scc

### ISSUE THREAD

**Issue by c02y** [boyter/scc#237]
**Describe the bug**

`go get -u github.com/boyter/scc/` won't install the latest version(v3.0.0)
**To Reproduce**

1. Tell us how you were using `scc` either as command line or library.
2. If command line please list the arguments. If library please supply code to demonstrate the issue.
3. If the issue is a miscount or some such please link or supply a file which demonstrates the issue.

**Expected behavior**
`go get -u github.com/boyter/scc` installs the latest version of scc

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux] Linux
 - Go version: go version go1.16 linux/amd64

**Comment by boyter** [comment]
Ah nuts. Something to do with tag versioning from memory. The annoying thing about Go is how this all changed with go mod.

**Comment by devfd** [comment]
@boyter I think you can either update the go.mod file with `module github.com/boyter/scc/v3` or make a new v1 tag

**Comment by boyter** [comment]
Oh interesting. I was trying to remember what I did with some of the other things I maintain for this and had forgotten. Something that's not instinct yet.

**Comment by boyter** [comment]
@devfd If you can do that it would help, or just put the instructions here. Either works for me.
