### ISSUE TITLE
Example CommandLine syntax to pass to get LLOC count

### ISSUE THREAD

**Issue by fignutz** [boyter/scc#245]
I apologize again for asking in this space, but what sort of syntax should be used/passed to SCC to get logical lines of code rather than physical lines? For example, I have the following snippet:

```
for (int i=0;i<10;i++)
{
}
```
In this circumstance, the logical count should be 1, but I'm seeing 3. Again, this is probably very simple, and I'm missing it, but any guidance on this would be helpful.

**Comment by boyter** [comment]
So there is no way inside scc right now to achieve this. Probably the easiest way would be to find some other tool that can collapse them as you want and count that way...

I don't know if I would be willing to add this support into scc either... the state machine to achieve it would be getting pretty close to being a parser at that point. Ill have a think on I though.

**Comment by fignutz** [comment]
Understood. I appreciate your candor on this, as LLOC/eLOC/SLOC is a big thing within some communities looking to get away from bigger solutions like SonarQUBE/Coverity.

**Comment by boyter** [comment]
@fignutz sorry about that. Its just more complexity than I am willing to take on at this point. I may change my mind in the future however, so its not a hard no, just a not right now.

Thats interesting. I have noticed a lot of the requests I get these days are to replicate some of the things that Sonar/Covertity do which explains that. If you have any links to those communities id love to go have a chat to them and see what I can do to assist there.

**Comment by fignutz** [comment]
> @fignutz sorry about that. Its just more complexity than I am willing to take on at this point. I may change my mind in the future however, so its not a hard no, just a not right now.
> 
> Thats interesting. I have noticed a lot of the requests I get these days are to replicate some of the things that Sonar/Covertity do which explains that. If you have any links to those communities id love to go have a chat to them and see what I can do to assist there.

Sadly, a lot of those communities are not public facing communities. That said, this link shows the current process users in those communities have to go through to add in support for proper LLOC counting of a new language that is not already supported in SonarQUBE: https://docs.sonarqube.org/latest/extend/new-languages/

**Comment by boyter** [comment]
Yeah the fact it starts with build a parser makes this mostly a non starter for me. But, I am starting to look at creating specific state machines for languages, in order to catch all the edge cases they have and as a way of improving performance. So it might be possible to consider adding this sort of logic in that process. Have linked this to the placeholder for that.

**Comment by fignutz** [comment]
> 
> 
> Yeah the fact it starts with build a parser makes this mostly a non starter for me. 

Indeed...this point is the reason that kept me and others from using it as well aside from vendor-lockin. Make no mistake, I personally feel that LLOC is a metric that can be relative, at best, when it comes to the worth/ingenuity/etc. of a coder: it is NOT a de-facto measure of how much work that coder has done. That said, there are people that still use this type of measure, for reasons rightfully or wrongfully, to help estimate their costs and pricing. 

Despite my own personal attitude on this, many of those types of folks have helped set precedents in certain areas that they've effectively locked themselves into for better or worse (e.g. they've always used LLOC size as a direct reflection of their performance when pursuing customers). All said, I appreciate you giving this type of thing thought all the same.
