### ISSUE TITLE
--exclude-dir cannot handle the slash at the end of dir

### ISSUE THREAD

**Issue by c02y** [boyter/scc#250]
**Describe the bug**
When I add slash at the end of dir of `--exclude-dir`, the dir is not excluded.

**To Reproduce**
```
# inside scc repo
>> scc --version
scc version 3.0.0
>> scc | rg Total
Total                      178     25942     3002      1729    21211       2327
>> scc --exclude-dir examples/ | rg Total
Total                      178     25942     3002      1729    21211       2327
>> scc --exclude-dir examples | rg Total
Total                       67     19263     1963       668    16632       1476
```
**Expected behavior**
`--exclude-dir` should handle that situation that the dir got slash at the end since most of the time I would just tab to complete the dir.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux] Manjaro-Linux
 - Version [e.g. 22] v3.0.0

**Comment by boyter** [comment]
Confirmed here. One for the next release. Thanks for the report.

**Comment by boyter** [comment]
Resolved in mainline. Sorry about how long it took to get around to this. Pretty crazy year.
