### ISSUE TITLE
JavaScript multiline comment /**/ should be added to vue multi line comment list

### ISSUE THREAD

**Issue by foxdd** [boyter/scc#253]
**Describe the bug**
As a vue file includes js language as well as html language, the javascript multiline comment token should be added to vue multiline list. Otherwise the JavaScript multiline comment will not be recognised

**Comment by foxdd** [comment]
By the way, single quotation mark also needs to be made as a member of quotes array of javascript language

**Comment by boyter** [comment]
Good point. Ill have a look through this more closely. If you want a fix now though send through a PR and ill merge it.

**Comment by boyter** [comment]
Resolved in master now. A build from there should fix everything.
