### ISSUE TITLE
Inconsistent results due to inconsistently ignored files

### ISSUE THREAD

**Issue by turgutsaricam** [boyter/scc#255]
**Describe the bug**
When repeatedly run, `scc .` command results in different counts. I believe this happens because of inconsistently ignored files. When `scc -v .` is run, you can see that the TypeScript files are *sometimes* ignored, while the ignoring must be consistent.

**To Reproduce**

1. Tell us how you were using `scc` either as command line or library.
    I am using the command in the command line. I installed it via Linuxbrew (`brew install scc`). I also created a Docker container by using the Dockerfile provided in the [`README.md`](https://github.com/boyter/scc#containers) and tested the command by attaching the project as a volume. Here is how I did it:
    ```shell
    # In the directory that contains the Dockerfile:
    docker build -t scc-test:latest --build-arg VERSION="master" .
    
    # Then, in the project directory, run this multiple times:
    docker run --rm -v "$(pwd):/home/project" scc-test:latest /home/project/
    ```
    This also results in the same inconsistent behavior.

2. If command line please list the arguments. If library please supply code to demonstrate the issue.
    I do not use any arguments. The command I run is `scc .` in the project directory.
3. If the issue is a miscount or some such please link or supply a file which demonstrates the issue.
    You can find the terminal output here: [scc-terminal-output.txt](https://github.com/boyter/scc/files/6372449/scc-terminal-output.txt) I attached a sample project that can be used to reproduce the issue: [project.zip](https://github.com/boyter/scc/files/6372448/project.zip) 
    - To reproduce, extract the zip archive and run `scc .` in the `project` directory multiple times.
    - When the command is run as `scc app/`, the inconsistency does not exist. 
    - When the command is run as `scc tests/`, the inconsistency does not exist. 
    - The inconsistency happens only when it is run as `scc .` in the `project` directory.

**Expected behavior**
I expected to see the same counts regardless of how many times I ran the command.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 20.04.2 LTS

**Comment by boyter** [comment]
Thanks for the reproducible test case.

This is something I am working on now actually, as part of dealing with the incorrect gitignore behaviour.

**Comment by boyter** [comment]
This should now be working inside the master branch and will make it into the next release 3.3.0
