### ISSUE TITLE
Feature Request: --exclude-ext

### ISSUE THREAD

**Issue by nemo1e8** [boyter/scc#259]
There's a feature to include only a certain set of extensions:
-i, --include-ext strings  

Would be nice to have an exclude counterpart that would allow you to exclude certain extensions instead. I often want to exclude e.g. text files from the count, and there's no simple way to do that if I want to retain all the other languages.

**Comment by boyter** [comment]
This has been added with the following option,

```
-x, --exclude-ext strings          ignore file extensions (overrides include-ext) [comma separated list: e.g. go,java,js]
```

Note that it will override --include-ext, so the following

```
scc -x go -i go
```

Would find nothing. You can get it by building from mainline.
