### ISSUE TITLE
Performance: Use os.File.ReadDir / DirEntry to avoid stat (go 1.16+) 

### ISSUE THREAD

**Issue by mpx** [boyter/scc#261]
Consider adding support for `ReadDir` and `DirEntry` (added in go1.16). This API often enables walking code to avoid `stat(2)` [[release notes](https://golang.org/doc/go1.16#os)]. A small `DirEntry` shim could be used to continue support for older Go toolchains (without the performance improvement).

Afaict, `DirectoryWalker` could avoid `stat` for directories, and ignored/excluded paths.

This is probably only a minor speedup in the common case since `os.FileInfo.Size` is used for processed files. However, it could be much larger when the ratio of non-processed to processed paths in high.

**Comment by boyter** [comment]
Yep pretty happy to have seen this come in. Just need to evaluate its impact on performance. Something to do for sure though.

**Comment by boyter** [comment]
Should be in there now using the new code.
