### ISSUE TITLE
Suggestion: add dml and ddl for SQL file-extensions

### ISSUE THREAD

**Issue by jhelberg** [boyter/scc#263]
Data Definition files and Data Manipulation files, part of the coiding effort, can be missed when using the filename-extension .ddl and .dml.

scc as a command-line tool will miss these.

The suggestion is to add "dml" and "ddl" to the list of extensions for the SQL-language as these are quite commonly used for these types of SQL files.

This needs editing of languages.json.

**Comment by boyter** [comment]
Sounds fairly reasonable. Got any examples of a common place this happens for testing? Also do you think perhaps they should have their own name?

**Comment by jhelberg** [comment]
I dont think their own name adds value. I edited the languages.json with respect to SQL to support extensions dml,ddl,dql,sql and some keywords which add complexity. I'll try and find some examples later:
  ```
"SQL": {
     "complexitychecks": [
      "select",
      "create table",
      "create or replace view",
      "create view",
      "with",
      "join",
      "case",
      "or ",
      "and ",
      "references"
    ],
    "extensions": [
        "sql", "dml", "ddl", "dql"
    ],
    "line_comment": [
      "--"
    ],
    "multi_line": [
      [
        "/*",
        "*/"
      ]
    ],
    "quotes": [
      {
        "end": "'",
        "start": "'"
      }
    ]
  },

```

**Comment by boyter** [comment]
Done. Now sitting in mainline. Feel free to build from latest to get this any all of the other fixes in there.
