### ISSUE TITLE
Language request: Racket

### ISSUE THREAD

**Issue by Seirdy** [boyter/scc#269]
Would be great to see support for Racket (.rkt) added to my favorite code complexity/size calculator.

**Comment by boyter** [comment]
I could have sworn I did add that at some stage. Might need to bust out git-bisect to confirm that thought.

Otherwise sure easy enough, although you could really help me out here by filling in the below correctly. I have copied the Scheme one which I guess should be fairly close.

```
"Scheme": {
    "complexitychecks": [
      "for ",
      "for(",
      "if ",
      "if(",
      "switch ",
      "while ",
      "else ",
      "|| ",
      "&& ",
      "!= ",
      "== "
    ],
    "extensions": [
      "scm",
      "ss"
    ],
    "line_comment": [
      ";"
    ],
    "multi_line": [
      [
        "#|",
        "|#"
      ]
    ],
    "nestedmultiline": true,
    "quotes": [],
    "shebangs": [
      "racket"
    ]
  },
```

**Comment by boyter** [comment]
Right starting to work on this now that everything else has been cleared up.

**Comment by boyter** [comment]
Done. @Seirdy would be great if you could have a sanity check of the output at some stage.

BTW big fan of your post https://seirdy.one/2021/03/10/search-engines-with-own-indexes.html :)
