### ISSUE TITLE
FR: Graphviz dot language support, ignore Graphviz generated SVGs

### ISSUE THREAD

**Issue by ajkq** [boyter/scc#271]
Is it possible to add support for Graphviz files (dot graph description language; extension .gv or .dot)?

It would also be great if Graphviz-generated SVG files could be ignored, especially if the .gv source files are in the same folder and have the same name.

SVGs have the following header:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.47.3 (20210619.1520)
 -->
```

OS: macOS 11.4
scc version 3.0.0

**Comment by boyter** [comment]
So pretty much XML then. Yep that should be possible.

Ignores... could be done though `.ignore` files which would be my preference, as someone may want to actually include it in the count.

**Comment by a-kohout** [comment]
The .gv/.dot source files are not xml.
A graph looks like this:

```
digraph {
    subgraph cluster_0 {
        label="Subgraph A";
        a -> b;
        b -> c;
        c -> d;
    }

    subgraph cluster_1 {
        label="Subgraph B";
        a -> f;
        f -> c;
    }
}
```
Here are a few [examples](https://graphs.grevian.org/example)

**Comment by boyter** [comment]
Oh right... I used them in the original post about scc... how the heck could I make that mistake. As for the ignored, yes that's totally possible now actually. 

Please forgive me, I have been off the coffee for the last two weeks and still trying to wake my brain up :)

**Comment by boyter** [comment]
Added into mainline so if you build from there and run it it should pick up .gv/.dot files. However I put it under the name "DOT" in accordance with what wikipedia calls it https://en.wikipedia.org/wiki/DOT_(graph_description_language) and not graphviz as the name. Hoping that works for you.

Let me know if you get odd results, but my initial checks showed it to be fine.
