### ISSUE TITLE
``--wide`` causes``--format json`` to be ignored

### ISSUE THREAD

**Issue by marwie** [boyter/scc#274]
**Describe the bug**
When running the following command `` scc --no-gen --no-ignore --no-large --no-min --no-duplicates --include-ext cs,shader,hlsl,cpp --format json --wide C:\git\my\project`` 
the output is not formatted as json

 - OS: Windows 10
 - Version 3.0.0

**Comment by boyter** [comment]
Interesting. Technically both are formatting options, and in this case the last one is being picked, which is probably correct, but I think in this case --format should override.

**Comment by marwie** [comment]
I see, I was hopeing --wide would add more info to the json as well. Would you consider that a feature request then?

**Comment by boyter** [comment]
The only thing you are not getting from the JSON that wide is giving you is the Complexity/Lines calculation. What is it you think is missing from JSON?

**Comment by boyter** [comment]
No response in a while. Everything is in the JSON other than the lines/complexity calculation which can be done based on the values in the JSON. Wide is just an output thing anyway.
