### ISSUE TITLE
Crash for missing config.json

### ISSUE THREAD

**Issue by crystalfp** [boyter/scc#278]
**Describe the bug**
Crash immediately on Windows even with a simple `scc --help`. Seems configuration file missing, but nowhere it is mentioned.

**To Reproduce**
```
$ npm i -g scc
$ scc --help
Caught exception: config.json missed!
C:\Users\mvalle\AppData\Roaming\npm\node_modules\scc\lib\scc.js:22
        console.log(err.stack.error);
                              ^

TypeError: Cannot read property 'error' of undefined
    at process.<anonymous> (C:\Users\mvalle\AppData\Roaming\npm\node_modules\scc\lib\scc.js:22:24)
    at process.emit (node:events:394:28)
    at process._fatalException (node:internal/process/execution:170:25)
```

**Expected behavior**
Well, that scc works. Or at least document the indispensable `config.json` file. Also having a program that crashes asking for help is not very helpful for the user.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Windows 10 64bits
 - scc version: 3.0.0

**Comment by dbaggerman** [comment]
Hi @crystalfp,

This isn't a node.js project, I think you might be looking for a different `scc`.

https://www.npmjs.com/package/scc indicates that the source is at https://github.com/gxcsoccer/scc - maybe that is the project you're looking for?

**Comment by crystalfp** [comment]
Sorry, was convinced this tool has also a npm package version. Not thinking of homonymy...
