### ISSUE TITLE
Does scc will have options to compare and provide the difference between files/directories?

### ISSUE THREAD

**Issue by mageshsankar** [boyter/scc#283]
Is there a way to view the differences between files/directories in SCC like there is in Cloc? In Cloc, we can compare two directories/files and see how many codes have been added, deleted, or modified. Is that option available in SCC? If so, could you please show me how to do it?

**Comment by boyter** [comment]
Probably the easiest way to do it would be using the SQL output option. Cloc supports this as well, so I suspect a lot of the queries should be easy to translate as well.
