### ISSUE TITLE
Question regarding terminology

### ISSUE THREAD

**Issue by romange** [boyter/scc#285]
Hi, 

regarding the `schedule effort` metric - is it measured in calendar months or people-months? 
Based on the cost I would say it's calendar months but I want to be sure.

Example from the readme:
```
Estimated Cost to Develop (organic) $6,918,301
Estimated Schedule Effort (organic) 28.682292 months
Estimated People Required (organic) 21.428982
```

**Comment by boyter** [comment]
I am pretty sure its person months, but my understanding of COCOMO might be flawed there. https://en.wikipedia.org/wiki/COCOMO

Looking at sloccount which I based a lot of it on, produces this output,

```
Total Physical Source Lines of Code (SLOC)                = 236
Development Effort Estimate, Person-Years (Person-Months) = 0.04 (0.53)
 (Basic COCOMO model, Person-Months = 2.4 * (KSLOC**1.05))
Schedule Estimate, Years (Months)                         = 0.16 (1.96)
 (Basic COCOMO model, Months = 2.5 * (person-months**0.38))
Estimated Average Number of Developers (Effort/Schedule)  = 0.27
Total Estimated Cost to Develop                           = $ 5,932
 (average salary = $56,286/year, overhead = 2.40).
```

Suggesting its person months, since the calculation is the same using the basic COCOMO model.

**Comment by romange** [comment]
Well, in the example above ~28 person-months that cost almost 7 million is a bit expensive. 
Also, based on this https://dwheeler.com/sloccount/sloccount.html#cocomo 
```
Next is an estimation of the effort and schedule (calendar time) it would take to develop this code.....
```
so the schedule is measured in time units while effort is measured in person-months.

**Comment by boyter** [comment]
Ah there you go.

Keep in mind it is only an estimate. You can tweak all of the COCOMO inputs if you like to get something closer to reality for you.

```
--cocomo-project-type string   change COCOMO model type [organic, semi-detached, embedded, "custom,1,1,1,1"] (default "organic")
```

and

```
--avg-wage int                 average wage value used for basic COCOMO calculation (default 56286)
```

would be the ones to modify.

**Comment by boyter** [comment]
Guessing nothing else to be done here. Closing.
