### ISSUE TITLE
Language Request: Solidity

### ISSUE THREAD

**Issue by vdrg** [boyter/scc#286]
Hello, I was wondering if it would be possible to include [`Solidity`](https://docs.soliditylang.org/en/v0.8.7/#) (.sol). It should be pretty much the same as `C`. I can send the PR if needed :)

Thanks for all the great work 💪

Cheers!

**Comment by boyter** [comment]
Send through the PR and ill ensure you get the credit! Otherwise ill get around to doing it at some point :)
