### ISSUE TITLE
Gitignore folders are not supported

### ISSUE THREAD

**Issue by aminya** [boyter/scc#291]
**Describe the bug**
If you have something like this in the gitignore:
```
folder1/folder2/
```
scc still counts the files under `folder1/folder2`.

**To Reproduce**

1. Add some files under `folder1/folder2`, and run `scs`

**Expected behavior**
It should support folders

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux] Windows 10
 - Version [e.g. 22] 3.0.0

**Comment by boyter** [comment]
Yeah its down to the lack of a reliable .gitignore parse for Go. 

I am aware and it's being worked on.

**Comment by aminya** [comment]
Some time ago, I wrote a Gitignore to Glob converter in TypeScript. If there is no such library in Go, I can try porting it. 
https://github.com/aminya/globify-gitignore

**Comment by boyter** [comment]
If you do @aminya ill be happy to use it. 

I started implementing one on this branch https://github.com/boyter/scc/tree/issue178 where I wanted to add ** support in, but ran into issues and moved on to some other issues. 

Having this as an external library that can be used by other projects would be extremely helpful! I have a few I would have use it instantly!

**Comment by aminya** [comment]
I have started porting it https://github.com/aminya/globify_gitignore. This is my first Go package, so any help is appreciated.

**Comment by aminya** [comment]
@boyter It is done! Could you test it and see if it works as expected:
https://github.com/aminya/globify_gitignore

**Comment by boyter** [comment]
Nice. Looking into it now. Will have some feedback in a few days.

**Comment by boyter** [comment]
Have not forgotten this, but got distracted looking into alternative file walk Go implementations. I might try applying this on one of my other projects first though, probably https://github.com/boyter/dcd since it should be easier to implement there.

**Comment by boyter** [comment]
Sample test cases to use with this https://github.com/svent/gitignore-test

**Comment by aminya** [comment]
I have written enough [tests](https://github.com/aminya/globify_gitignore/blob/master/lib/lib_test.go) to ensure the functionality of the library. But we can always add more. The repo you sent takes an interesting approach to test this. It requires some work for integration.

**Comment by boyter** [comment]
@aminya I tend to use a mix of unit and integration tests to ensure everything works as expected, and I can use it to compare against other tools such as rg, ag and git itself.

I have started here with the integration work, https://github.com/boyter/goignore which I would love you to have a look over as I am 100% certain I am doing something wrong. However the results are starting well with,

```
$ goignore
>>> .gitignore
2 foo: FAIL
2 foo: OK
2 foo: FAIL
2 foo: FAIL
2 foo: FAIL
2 foo: OK
2 foo: FAIL
2 foo: FAIL
2 foo: FAIL
2 foo: FAIL
2 foo: OK
2 foo: FAIL
2 foo: FAIL
2 foo: FAIL
2 foo: FAIL
2 foo: FAIL
2 # gitignor
>>> .gitignore
5 foo: FAIL
5 # exclude
5 foo: FAIL
5 foo: OK
>>> .gitignore
2 foo: FAIL
2 !*.html
2 foo: OK
2 *.[oa]
*.h
2 foo: FAIL
>>> .gitignore
3 foo: OK
3 !/vmlinux*
2 foo: OK
2 foo: FAIL
2 foo: FAIL
2 foo: OK
2 foo: FAIL
2 foo: OK
```

Which is not a bad start. Note that this is using the new Go file walk methods as well.

**Comment by boyter** [comment]
Actually I note I get a lot of the following error (which is to be expected)

```
error parsing regexp: invalid nested repetition operator: `**`
```

As there are a lot of double ** in there. This is another bug I have been tracking https://github.com/boyter/scc/issues/178 which needs to be resolved. I suspect I am using your library incorrectly @aminya

**Comment by aminya** [comment]
You should use a glob library. Do not use regexp to match paths. 
Something like
https://github.com/gobwas/glob

**Comment by boyter** [comment]
Done. 

Although this is speaking to my ignorance of gitignore and its patterns, and one of the reasons I have put this off so long. Is the full path needed to be passed into the patterns? How does this work for nested gitignore files?

**Comment by aminya** [comment]
No worries. I should have added the glob integration too to eliminate the confusion. 

Glob patterns can be summed up together. So, the approach for supporting nested git ignore files is to:
1) Find all the gitignore files using a glob pattern like `**/.gitignore`
2) Pass their paths to `globify_gitignore` so it reads and parses each. 
3) Concatenate all the arrays returned by `globify_gitignore`
4) Pass the big array of glob patterns to the glob package to get a whitelist of the paths that should be analyzed.

If you did this let me know, and I will be happy to merge it to `globify_gitignore`.

**Comment by theodorejb** [comment]
Is there any progress on this, or a workaround to reliably ignore a list of folders?

**Comment by boyter** [comment]
No progress yet sorry. Been too busy on work projects and have not had time outside of work to actually put time on this. It is on my list of things to do.

If you want to ignore folders, you can however put .ignore files where the folder is with the folder you want to ignore in it. If you don't use globbing rules this should work as is.

**Comment by boyter** [comment]
Relates to https://github.com/boyter/scc/issues/261

**Comment by CarterLi** [comment]
Move this to **Release 3.3.0**?

**Comment by boyter** [comment]
My bad. I really need to get back on this one. The annoying this being the amount of logic around this, meaning its going to need a fair bit of effort to ensure it works.

**Comment by boyter** [comment]
OK this should now be sitting in master if someone cares to validate it.

**Comment by boyter** [comment]
NB I will be closing this down in a few days once the new release is pushed out.

**Comment by boyter** [comment]
Closing now as all appears well.
