### ISSUE TITLE
Way to add a badge in Gitlab ? 

### ISSUE THREAD

**Issue by AlexandreHerbreteau** [boyter/scc#301]
Hi all.

Provided example in the documentation on how to add a badge with Line of codes is not working on Gitlab.
Could you please give an example on how to do so in Gitlab ?

**Comment by AlexandreHerbreteau** [comment]
![image](https://user-images.githubusercontent.com/4036175/140103692-e623ca05-e8e6-47b8-bace-2adbe09bc8df.png)

**Comment by boyter** [comment]
You should be able to use the URL like so,

https://sloc.xyz/gitlab/esr/loccount/

Where you need to replace esr with your gitlab username and loccount with your project name. If you are able to list them here I can probably work it out.

**Comment by AlexandreHerbreteau** [comment]
Thanks for the answer. Understood, I think I got it: it only works for a public project. Mine isn't.
:(

**Comment by boyter** [comment]
Ah yes sorry about that. You would have to do it yourself for a private one. You can get how it works here https://github.com/boyter/scc-lambda

**Comment by AlexandreHerbreteau** [comment]
Hello Ben.
Thanks for your answer.

With your link and the simple documentation (build + install with pip), I'm
not able to figure out how it works to integrate it on Gitlab.
Sorry about that, do you have any more clues ?

**Comment by boyter** [comment]
You would need to see if you can put your SSH keys or username + password into the git install that the lambda layer uses. Not sure if I can do more to help there sorry to say. You could also run it on a server yourself, but that would be a bit more work.
