### ISSUE TITLE
Feature request: OpenMetrics report format

### ISSUE THREAD

**Issue by jan-guenter** [boyter/scc#306]
### What's OpenMetrics?
OpenMetrics is a metric reporting format specification extending the Prometheus exposition text format.
Homepage: https://openmetrics.io/
Specification: https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md

### Why I want support for OpenMetrics in scc?
I'm a DevOps engineer and our DEVs like to use scc for code metrics generation in our CI pipelines.
We are using GitLab and Prometheus. Both can natively interpret OpenMetrics reports.

Currently I use a separate step in our CI pipelines transforming sccs JSON output into an OpenMetrics format.
This requires an additional dependency to the JSON query cli tool [jq](https://stedolan.github.io/jq/), which I would like to eliminate.

### Desired Implementation
I suggest an additional format value named `openmetrics`.
This will output the metadata information for the scc metrics followed by the metrics data.
The reporter should respect the `--by-file` parameter.

**Comment by boyter** [comment]
Sounds good to me. I am not familiar with OpenMetrics, but happy to include this.

Merged in and it will make it into the next offical release, which should be sometime next year.

**Comment by jan-guenter** [comment]
Excellent.
Closing the issue.
