### ISSUE TITLE
`aggregateLanguageSummary` returns `nil` instead of an empty slice

### ISSUE THREAD

**Issue by jan-guenter** [boyter/scc#308]
In my PR #307 I introduced an error:
`aggregateLanguageSummary` returned `nil` instead of an empty slice in case of an empty input.

Sorry, my inexperience in Go fired back.
I was not really aware of the differences between:
```go
language := []LanguageSummary{}
```
and
```go
var language = []LanguageSummary
```
and blindly trusted the coding recommendation of GoLand to prefer the non-allocating version.

This issue caused the unit test `TestToJSONEmpty` to fail which I missed amongst all the other test currently failing in master.

**Comment by boyter** [comment]
Ah yes I run into that a lot with Goland myself. Not a huge issue.

**Comment by boyter** [comment]
All unit tests should be resolved now to assist with this in the future.
