### ISSUE TITLE
Option --exclude-ext not available

### ISSUE THREAD

**Issue by mosser** [boyter/scc#310]
**Describe the bug**

I am running `scc 3.0.0.` installed using Homebrew on a Mac (Monterey 12.1, Homebrew 3.3.9). When calling `scc -h`, it does not expose the `--exclude-ext` option that is documented in the README.md file.

**To Reproduce**

```
mosser@loki test % scc -h | grep exclude
      --exclude-dir strings          directories to exclude (default [.git,.hg,.svn])
```

**Expected behavior**

According to the documentation 

```
mosser@loki test % scc -h | grep exclude
      --exclude-dir strings          directories to exclude (default [.git,.hg,.svn])
  -x, --exclude-ext strings          ignore file extensions (overrides include-ext) [comma separated list: e.g. go,java,js]
```

**Desktop (please complete the following information):**
 - OS: MacOs X
 - Version 3.0.0

**Comment by boyter** [comment]
My bad. This is a new bit of functionality in the forthcoming 3.1.0 release. I have updated the README to reflect this.

You can build from source if you urgently need this functionality, or wait for the next release.
