### ISSUE TITLE
Error message "file or directory does not exist:" with an existing directory

### ISSUE THREAD

**Issue by HFTrader** [boyter/scc#315]
**Describe the bug**
The command `scc /tmp/linux` always produces the answer `file or directory does not exist: /tmp/linux` even if /tmp/linux is a directory where I have full access. That's the repo where the linux kernel has been cloned.

**To Reproduce**

1. scc is being used in the command line. 
2. Command line argument is just the directory `/tmp/linux`
3. scc responds with the error above and quits, producing no results

**Expected behavior**
I expected scc would examine the files within the folder and print a summary.

**Desktop (please complete the following information):**
 - OS: Linux KUbuntu (KDE) Focal 20.04.03 LTS
 - Version 3.0.0 (snap)
 
![Screenshot_20220117_063806](https://user-images.githubusercontent.com/11621271/149770894-15fb9c0d-0780-4f69-91a9-2fd351c4b8d7.png)

**Comment by boyter** [comment]
Now thats an interesting result. I run scc against /tmp/ all the time without issue.

**Comment by HFTrader** [comment]
The only difference I can think of is that this folder is in /tmp which is tmpfs.  I have other git repos in $HOME that scc works just fine. But I also have another NVME mount in /ssd where scc also fails with the same permission error.
So something about these partitions scc is not happy about but it likes home somehow.

**Comment by HFTrader** [comment]
Ok so this seems not to be related to scc after all. As scc on Ubuntu is installed with snap, it will not be able to read anything outside /home. The solution is to use everything within home or install scc from another source. However scc is not available through apt-get so the only solution is really to compile from sources on Ubuntu if you want to use scc outside /home.

https://askubuntu.com/questions/930437/permission-denied-error-when-running-apps-installed-as-snap-packages-ubuntu-17

**Comment by dbaggerman** [comment]
> However scc is not available through apt-get so the only solution is really to compile from sources on Ubuntu if you want to use scc outside /home.

Golang binaries have minimal dependencies, so grabbing the precompiled linux binary from https://github.com/boyter/scc/releases and dropping it somewhere in `$PATH` should work on most distros. The only reason I've seen it not work is when the distro uses an alternative libc (such as alpine docker containers).

**Comment by boyter** [comment]
As @dbaggerman says, its a simple binary, so pulling that down and putting into your path should work for you.

I'll update the README.md to point out the potential snap issue for the future.
