### ISSUE TITLE
GC Settings bleeding through API

### ISSUE THREAD

**Issue by boyter** [boyter/scc#32]
See https://github.com/pinpt/ripsrc/releases/tag/3.1.0 

This should never have happened. Refactor so that this is only set via command line usage and not though API.

Also a big apology to @jhaynie for this.

**Comment by boyter** [comment]
Once again sorry about the lost time @jhaynie I hope that the next release makes it up to you with what I am hoping is double the performance.

**Comment by jhaynie** [comment]
No worries dude! Appreciate the fix. You’re doing AWESOME work

**Comment by boyter** [comment]
Thanks for the kind words! :)
