### ISSUE TITLE
Feature Request: Svelte Lang support

### ISSUE THREAD

**Issue by Chaostheorie** [boyter/scc#326]
As the name implies, counting support for [svelte](https://svelte.dev/) lang. Svelte is a web framework for reactive apps that employs it own JSX-like file format. The file format mostly behaves like HTML with some special properties for reactivity etc, and support for preprocessors for script (TS, CoffeeScript, …) and style blocks (PostCSS, SASS, …). It would be a nice addition to the list of supported language, as I've found no other LOC counting tool with support for it.

The file format can most likely be counted in the same way as HTML. I unfortunately don't have any knowledge about Go, but will help if possible.

Even if the request gets rejected, thank you for this awesome project.

**Comment by boyter** [comment]
Good news! Svelte is in for the next release (which will happen the moment I finish the git stuff, or if someone does it for me).

You can see the definition for it here https://github.com/boyter/scc/blob/master/languages.json#L6039 

BTW adding languages is fairly simple, you just need to know how to edit JSON. If you want to have a look at the above you should be able to see how it works and determine if thats working for you :)

If you need this now, you can always build from the mainline branch :)

**Comment by Chaostheorie** [comment]
Thank you for the quick answer. Svelte support sounds awesome and I'm looking forward to the next release. I eventually settled for cloc for the required tasks but I'll test scc asap.
