### ISSUE TITLE
SQL format is broken

### ISSUE THREAD

**Issue by alexey-milovidov** [boyter/scc#333]
**Describe the bug**
See also #332.

**To Reproduce**

https://github.com/microsoft/TypeScript
`'tests/cases/projects/Quote'InName/m'ain.ts', 'tests/cases/projects/Quote'InName/', 'm'ain.ts', 81, 1, 1, 2, 0)`

**Expected behavior**
Should properly escape quotes in SQL.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 3.0.0.

**Comment by alexey-milovidov** [comment]
nvm-sh/nvm:

`'test/slow/nvm use/Running 'nvm use --lts=foo' uses latest 'foo' LTS version', 'test/slow/nvm use/', 'Running 'nvm use --lts=foo' uses latest 'foo' LTS version'`

ansible/ansible:
`'docs/docsite/rst/scenario_guides/vmware_rest_scenarios/task_outputs/Turn_the_NIC's_start_connected_flag_on.result.json', 'docs/docsite/rst/scenario_guides/vmwa`

**Comment by alexey-milovidov** [comment]
I need at least one machine-readable format. Either CSV or SQL - does not matter. At least one format should work correctly.

**Comment by alexey-milovidov** [comment]
ReactiveX/RxJava:
`'docs/What's-different-in-3.0.md'`

**Comment by adam-moss** [comment]
I hit this in one of our projects, where `File_dirname` was returned as `'{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_')  }}/pyproject.toml'`

**Comment by boyter** [comment]
Resolved in master branch f06af573f5fd6c9ab88b86267512d68bf09b8dd5 and will make it into the next release.
