### ISSUE TITLE
MATLAB counted as Objective C

### ISSUE THREAD

**Issue by kwsp** [boyter/scc#339]
**Describe the bug**

Both MATLAB and Objective C source code use the extension `.m`, but all MATLAB code is counted as Objective C

**To Reproduce**

Run `scc` in a repo with MATLAB source code.

**Expected behavior**

Show language correctly.

**Desktop (please complete the following information):**

 - OS: All
 - Version: All

**Comment by boyter** [comment]
@kwsp Don't suppose you have an example repository to assist with this?

**Comment by kwsp** [comment]
Yes! https://github.com/kwsp/scc-bug-matlab

I added one MATLAB source file and one Objective C source file.

**Comment by boyter** [comment]
Perfect. I can use this as a test case, cheers.

**Comment by boyter** [comment]
OK I think this is working now. It probably still will have issues on your sample @kwsp but it should be far more intelligent for larger files.

If you are able to build from master could you give it a try please? Its possible I missed some of the keywords in MATLAB to assist with it determining the language, but this can be improved if we find edge cases I think.

**Comment by kwsp** [comment]
@boyter I just tested master on a private code base and it works very well!

**Comment by boyter** [comment]
Well that makes me VERY happy @kwsp 

Ill consider this done then.

**Comment by kwsp** [comment]
In Matlab keywords, you have 'function' twice. Maybe remove it to save a few extra ticks of performance? :)

**Comment by boyter** [comment]
Ah so I do. Resolved. I might add code later to strip those out such it shouldn't make a difference.
