### ISSUE TITLE
Support for Additional Language: TEAL

### ISSUE THREAD

**Issue by rolegic** [boyter/scc#342]
- language name: **TEAL**
- file extension: `.teal`
- method of commenting text: `//` prefixes a line comment
- location of sample code:
  - [Assembler Syntax](https://developer.algorand.org/docs/get-details/dapps/avm/teal/specification/#assembler-syntax)
  - [Example walkthrough of a TEAL program ](https://developer.algorand.org/docs/get-details/dapps/avm/teal/#example-walkthrough-of-a-teal-program)
  - Basic sample [Looping and subroutines](https://developer.algorand.org/docs/get-details/dapps/avm/teal/#looping-and-subroutines)
```
#pragma version 4
// loop 1 - 10
// init loop var
int 0 
loop:
int 1
+
dup
// implement loop code
// ...
// check upper bound
int 10
<=
bnz loop
// once the loop exits, the last counter value will be left on stack
```

Thank you for this useful and valuable tool.

**Comment by boyter** [comment]
Added in https://github.com/boyter/scc/commit/295dcccbe860e51114e44a063702d64331a65bad

Build from master and teal should now appear. Thanks for the kind words and helpful request.
