### ISSUE TITLE
`SCC WebApi`

### ISSUE THREAD

**Issue by ErnestFistozz** [boyter/scc#347]
Hi,

Does SCC have a Web Api? I would love to run some analysis on a couple of repositories on GitHub remotely without downloading or installing the tool and cloning the repo.

**Comment by boyter** [comment]
Currently no. There is https://github.com/boyter/scc#badges-beta which can do this, but I need to redo that due to the personal cost to me.

Its something I would like to do, but ultimately it is likely to get abused so without someone helping pay the bills for such a thing I am unlikely to offer it sadly.

**Comment by jolav** [comment]
> Does SCC have a Web Api? I would love to run some analysis on a couple of repositories on GitHub remotely without downloading or installing the tool and cloning the repo.

I have been offering this web service for almost 6 years.
Until a couple of years ago I used https://github.com/cgag/loc but then I switched to scc.
You can check it : https://github.com/jolav/codetabs


> Currently no. There is https://github.com/boyter/scc#badges-beta which can do this, but I need to redo that due to the personal cost to me.
> 
> Its something I would like to do, but ultimately it is likely to get abused so without someone helping pay the bills for such a thing I am unlikely to offer it sadly.

I can assure you it's a pain in the ass.
I had to limit downloading projects that are smaller than 500MB.
I have had months with more than 100 TB of incoming traffic. On average it will be about 40
Sometimes github is slow or penalizes you for abusing.
You have to carefully manage request timeouts.
I'm thinking of rewriting it using a queue system. But I'm still figuring out how to do it.

**Comment by ErnestFistozz** [comment]
@jolav thanks, this is exactly what i am looking for. I will try it out.

**Comment by boyter** [comment]
> > Does SCC have a Web Api? I would love to run some analysis on a couple of repositories on GitHub remotely without downloading or installing the tool and cloning the repo.
> 
> I have been offering this web service for almost 6 years. Until a couple of years ago I used https://github.com/cgag/loc but then I switched to scc. You can check it : https://github.com/jolav/codetabs
> 
> > Currently no. There is https://github.com/boyter/scc#badges-beta which can do this, but I need to redo that due to the personal cost to me.
> > Its something I would like to do, but ultimately it is likely to get abused so without someone helping pay the bills for such a thing I am unlikely to offer it sadly.
> 
> I can assure you it's a pain in the ass. I had to limit downloading projects that are smaller than 500MB. I have had months with more than 100 TB of incoming traffic. On average it will be about 40 Sometimes github is slow or penalizes you for abusing. You have to carefully manage request timeouts. I'm thinking of rewriting it using a queue system. But I'm still figuring out how to do it.

Ah well that's probably something I won't be doing then. I have enough on my plate as it is... dealing with that sort of traffic sounds like fun though! Ill add you as a link if someone is looking for this sort of thing though.

**Comment by ErnestFistozz** [comment]
Closing the issue as it has been discussed.
