### ISSUE TITLE
How to install v3.1?

### ISSUE THREAD

**Issue by thegoatherder** [boyter/scc#349]
**Describe the bug**
The documentation for this module shows `v3.1-beta` on the list of `scc` commands. However the `scc@master` version installs v3.0.0. Several commands shown in the documentation on github `master` branch are missing when installing `scc@master`

For example, these cli parameters are missing:
```text
-x, --exclude-ext strings          ignore file extensions (overrides include-ext) [comma separated list: e.g. go,java,js]
--currency-symbol string       set currency symbol (default "$")
```

**To Reproduce**

In powershell on windows:

```powershell
PS> go install github.com/boyter/scc@master
PS> scc --version
scc version 3.0.0
```

```powershell
PS> go install github.com/boyter/scc@latest
PS> scc --version
scc version 2.12.0
```

**Expected behavior**
I would expect the output of `scc -h` to match the one in the documentation on `master` branch when installing `scc@master`

**Desktop (please complete the following information):**

```text
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
```

**Comment by boyter** [comment]
So 3.1.0 is still in development, so installing from master should in theory produce that... I think this is due to the versioning issues with tags and such.

I am going to use GoReleaser for the next version which should in theory resolve all of these issues.

**Comment by 89z** [comment]
would you be willing to make an interim release, such as v3.0.1? Looks like its been over a year since the last release, with over 100 commits:

https://github.com/boyter/scc/compare/v3.0.0...master

**Comment by boyter** [comment]
@89z I am getting close to that point. I really wanted to get in the proper handling of globbing in git however it might be better to get everything else in now and move that into the next release.

**Comment by boyter** [comment]
Done. @thegoatherder and @89z that should work for you now I hope.

**Comment by 89z** [comment]
thank you!
