### ISSUE TITLE
Feature request: FSL (new language)

### ISSUE THREAD

**Issue by StoneCypher** [boyter/scc#351]
**Describe the bug**

I would like it if you would include my language, `FSL`, as implemented by `JSSM`.

The language is not sensitive to extensions, but `.fsl` is almost universal, and as far as I know not conflicted.

&nbsp;

**To Reproduce**

Run `scc` against a codebase containing `FSL` code.

&nbsp;

**Expected behavior**

A line count of `FSL` code, please.

&nbsp;

**Desktop (please complete the following information):**

- OS: Windows 
- Version: Windows 10 Pro 64

----

# Code samples

If you prefer, you can test against [this mixed-language repo](https://github.com/StoneCypher/jssm), which has `FSL` in `./src/machines/`.

A trivial example of FSL code:

```fsl
on <-> off;
```

----

A larger example:

```fsl
Off 'enable' -> Red;
Red 'next' => Green 'next' => Yellow 'next' => Red;
[Red Yellow Green] 'disable' ~> Off;
```

----

A genuinely large example:

(you can see this rendered [here](https://stonecypher.github.io/jssm-viz-demo/graph_explorer.html?s=LYQwxgFglgdgpgfRiYcAEGMC40CIDKEA9gK4A2AJmgJ6lokDO6ALgO5TPNwBOA-LgG4AsAChQkWIhAlmxbphy4AsuGgxCsNAB5xahmoACAc1BQyAOjBFgAPkGjdkhGShg4MJtjRKAkgBVhMVUnK2BUGGYvXABiUAo4dlkAMwYyeyCJeGcQGCMSECN0HHdAxyyANx4GKCIYLwBGcwAGZsCUsgRK7mrazAU0RpamwNEGZhBuZgQxkC4GPrQcAG18ccmAXRGRdwpp8bmFryXRDFwATTowHLQAazg4AAcaUnk-RK55cCsSCNwTvAA4nBIkQkkk0G8OB80DkqEw4Dc0BA4GQHn8RKd8ERuNxqBD3jw0AArRiRKAMGAAckiSWxzxI6NOQJBYPxUJ4jLwKmoACN0LQSGh9KRKELmK5EcwiGgAGLgOA8ohEG7ozaiUSrCaRAC0NjwPnmAteBPktPkDyqtRAZDQdJ5jEkDHmjDg-ECuAN9ON7NNdIt3StNrtDvgTvoTH4aEpAAVLcgyJS0P8MLq8AARaUCpEgSow7M8ji28HcOCVa2wIxoWDi0BcND+hiBtDxcZmBhu0Qew0vNmcQlm+tx622+T26qh50R3BRgBCIbgTsTybQqdwAEES-TwxXe9CpWhQsAfq5ZnAADp1RIQA+k6xVGEwOE7NA87iw+gPCin9vpLte3f9n6Q5BqO85hi6kaUkoeJjo68zkoOAbxpSyarhmW4UOS4q5CQ5LXkaL5gfMXykBEF5oEk3DWP+DZNiRPzMB2IiduhWYQDm6AgPmhagmgJZli4uRVhEUC1ugtHxs2wIgG2kEAHJEAANGgPjZrmXEPCWnB4kYSpUCABYuMweL7kwZDglYERUQm-yrhunFoKARLYhweK8QRbD3Mw8ERDwC7YUYinkUkPwwNQyl0rIpBGBAzDappRDlMqFZMRgLGZnQ7HqdxLJ8aWcDlkJ1aiaeiGNpJLYyWQP5RgA8jAZB4qwyJ1KpWXoOx+loEZzBkCwSqIkekBoPuFDcLANwoRiK56rgGYLv+iphrSZBkEQrD0kx6ULQRS3zCta0bQKkFnAuU19KuzJFuCkJ9twv7zd2JCjkQy1EKt62bdOlIKedmB2ZuWYkmM25Cbde7SjMZCIm4fWvhwC6RpdwLXQBnyPkK9yIsiqLpJ29l5k5LnGUW-6ecCPkfP5FZBXUIUwGFEXyFFJAxXFCVJTcKXfQpymyHAeITOgwCvb1eIPK48y8cAeJkD8w10jLB6zH9KazQTWZcbDCrjcZ6R9Pjm5cUTutueCHmsF5lN+WMNPBaF4UjiNxCs7F8VUZz3NRqdDCqzNeAa5cIAPAZfWk3cjw7gRsDVGzDDkfu9QACxNAe7FvmAHxS6aCQ8FtIjroDdBayiOuuTzRB+6u3J8luwrkHC4pgJK0pym4irKr+geCiXcOm99PtV7NFyClcdQR08BHg4S9G-Fsc0ZYKmG2zheGLURMJgN8ZF01RwA0cBm-b4xFcRRZLyeDARDMEPgIo6CN0mvrmDpRhWEVrh+jr+OC7EVvpHMGCnvA+SFhyzxPt7M6y4Ab8joCGSs09mbSkPMeK4XByJXhvGMO83QHxPgxq+d8JBPzfnzoXWBgp4FoxGsg6wR4YAnnQZeDg14wC3lQLg98TACFvgxsQr8cx5JKTQFfSIcAAAe4Axa33OHAx8VRxgY2arMah5JlLjTZmQ7uoMEEmhoQeOhqDTwYJYVgqUHDiIY24VQQhfCSGCIHlA6aat0zSmNiAZyptSYETAC4dw3knZsOwRYvKqBgB8mZsiNAukiBUHelQL81Apbgn5mgAAwkqFwFBChoDXBQYAsAsJvnFLUMh6F3GeNct4nsvioD+OzmYnB8wSxhIic7dAMS4mikSck9p6TMlQGyegPJBSGFjGKTUGAQiZEAAlPqgi4HUCgi8RqW2BGUtxjkPHEzNv+Wp9TAnsPvC0uA4TCSpM6babpIAkmk1SRk96gyckjMKeM2YkyToLmUu+fmUBTR-JBgAL0eBaQSfFBlwBkViHEeJEHElJFWCk1IKJ0gFHjAuI9lbj3uJPHscLwHTi0Nqf4lJB6uK3C4O4+ibhXw2sosk8xdI7l6JoVJrBsSUHIgAVm1AANkcrAGQC0+Rmk4mFNA7LuCingKwKWMg+on3dJisetwcX-nxf-BihLtSQN9gHI2WzKkk3cj2cm3lyIljIKeKg+5dobzpLACgpJcQbIpVAKl+4aWfXpYi6JRBmV1FZVEyVnK6g8v5aMoV8wRXYjFU1DlVAZVyt6usiuf1VzQtxNQ4GDKqQ0lRaQLuBqTZVJNc9VZVs8pWq4BQBOi9QI-zDA6x8zrqDTNsrNTNsK9E5sRXmlF8g0Xz1YnQWojVVWPDJno8BwVIpRO4IwfCdAkj3BtM1dwU6vK+q0msmtnzfYdrwAAJQKqtNt6LcAnutI1fd6bZpXQftQrhWMkQojRO6K9Z723TTQissdeIJ5Tp9EfABs7InoAXV-LMK6UQSpapulGCEd1eTgBQLRRdR7B1DugXiE8o49hjlAOOdaBgpzThMKR946QrstnwTkv6tz-onbi8tbBgMzrpnOiDi6twwbXfBi2W6kPAl3ah-OnYH2skQdqyBIAl2YddpEVAiZcAAHUZI6lyRhoUId950i4oqRVJw1MaZXFpihOmUBOwM9faZ-tcBzI2gsjdyytxmtSiZwsOrtEMF09Zl8tmZOkrOngTFPx4jdEUVQH1cK1Hgs0frYzjmiyLObCs9z30ZkTAoOO-K3AZHaN7VQuFplxjQwPKXeGDjAh4GS85pZ6Xd2QXqFykaokFrG1qLIGRI7BRMcAxbdjmqd4Dr6ZB+TFFV1wY3YJxDzSRMobQ4IJMGIHPzKSKl1zWYMtRjXGQEWIM8vUESQV4t2yvFluZru+OdRLXWv0XaxtDTHWtvE8xEQAB6D7YA3ryBmHMdUIh-voEvaem9uAcAAG9-j6GDnAHARBM4FFqDVl84AbhGCouF7UVg1rcBwDyK1zdUdcHEXFXH2IcDNQRoEAAvlsYHXIbm1yzPXUUttm76LbgqAaEO0DQ+mrDi0COke6RgKjnk6PMekQoDj96lOhQ3F5HLOAJOJHk-l-juDNPRD08B6MfYIPJOPx9HzgXGAhfw9tKLlH-xJfN2l9jinWuGBK8JyQVX-xSca7x1T6AXA6dbAN6VXAxun1WJfTjNEUOYfsWF9b8YYuJdS6x4+OXvvFfK492rsn6eFfU4D7rhnhvQtB2xZOqe07hvMDN7HuHIvE+2+mvbjHqfZfO5wK7rPnvpre7z1rgvPe9fvcZwQbEWa4W9vJP2gcaKY+C7j1bxHjfxd25TzL-vne3cq5zz7-P-uh-F5D49Rar19rvUOl9RY-O6-x+X8j1fzf19O81zgagKJDqB8B4zzUkxr-m7Rwdzb372vxcFQEx3uEfwwD72d0OGv0H1R0tzgIWAbwf1R0En8moDDjgJwC-H0FQy-xECAA))

```fsl
machine_name     : "Should you use twitter?";
machine_author   : "MachinShin <machinshin@gmail.com>";
machine_license  : MIT;
machine_comment  : "#madewithfsl";
machine_language : en;
machine_version  : 1.0.0;
fsl_version      : 1.0.0;

start_states     : [Start];

end_states       : [
  "You can keep your Twitter account"
  "Get off Twitter and seek help"
  "Sorry Twitter just isn't for you"
  "Get off Twitter"
  "Maybe you should stick to Facebook"
];

Start -> "Is your Twitter for personal or business use?";
"Is your Twitter for personal or business use?" 'Personal' 
    -> "Do you have a habit of revealing intimate personal details?";
"Is your Twitter for personal or business use?" 'Business' 
    -> "Are you using Twitter to communicate\n with customers and send brand updates?";
"Is your Twitter for personal or business use?" 'My business is personal'
   -> "Do you distinguish your business account\n from your personal account?";

"Do you have a habit of revealing intimate personal details?" 'No, I have a pretty good ability to self control'
  -> "Are a majority of your tweets interesting,\n funny, or thought-provoking?";
  
"Do you have a habit of revealing intimate personal details?" 'Only when I have had a little took much to drink'
  -> "Does your boss follow you?";

"Does your boss follow you?" 'Yes'
    -> "Get off Twitter";
"Does your boss follow you?" 'No'
    -> "Are you just using Twitter to stalk celebrites?" -> "Get off Twitter and seek help";

"Are a majority of your tweets interesting,\n funny, or thought-provoking?" 'No, they are mostly pics of my lunch or my cat'
    -> "Are you a celebrity";
    
"Are a majority of your tweets interesting,\n funny, or thought-provoking?" 'Yes'
    -> "Are you capable of keeping your insights\n to 140 characters or fewer?";

"Are you a celebrity" 'No'
    -> "Maybe you should stick to Facebook";
"Are you a celebrity" 'Yes'
    -> "You can keep your Twitter account";

"Do you distinguish your business account\n from your personal account?" 'No, of course not'
    -> "Get off Twitter";
    
"Do you distinguish your business account\n from your personal account?" 'Yes'
    -> "Are you using Twitter to communicate\n with customers and send brand updates?";

"Are you using Twitter to communicate\n with customers and send brand updates?" 'No, not exactly'
    -> "You understand what Twitter is, right?";

"Are you using Twitter to communicate\n with customers and send brand updates?" 'Yes'
    -> "Do a majority of your clients or customers remember the good old days of the Coolidge Administration?";

"Do a majority of your clients or customers remember the good old days of the Coolidge Administration?" 'No'
    -> "How often do you tweet?";

"Do a majority of your clients or customers remember the good old days of the Coolidge Administration?" 'Yes, and their first zeppelin ride'
    -> "Sorry Twitter just isn't for you";

"You can keep your Twitter account" <-
  'Yes' "Do you like to know what is going on in the world\n 5-6 minutes before any world news outlet?";
"You can keep your Twitter account" <- 'Yes' "Are a majority of your tweets\n related to your business or industry?";

"Do you like to know what is going on in the world\n 5-6 minutes before any world news outlet?" 'No'
  -> "Sorry Twitter just isn't for you";
"Are a majority of your tweets related\n to your business or industry?" 'No'
  -> "Sorry Twitter just isn't for you";

"Do you only keep your twitter account\n for the rush you feel when your tweet is retweeted?" 'Yes'
  -> "Really?";

"Really?" 'Yes'
  -> "Get off Twitter and seek help";
"Really?" 'No'
  -> "Do you only keep your twitter account\n for the rush you feel when your tweet is retweeted?";

"Are you capable of keeping your insights\n to 140 characters or fewer?"
  -> "Do you only keep your twitter account\n for the rush you feel when your tweet is retweeted?";

"Get off Twitter" <- 'Yeah you caught me' "Wait - Are you spam or a bot?";
 "Wait - Are you spam or a bot?" 'No' -> "How often do you tweet?";
 "Wait - Are you spam or a bot?" <- 'Yes' "You understand what Twitter is, right?";
 
 "How often do you tweet?" 'Hardly ever'
    -> "Are you just using Twitter to stalk celebrites?";
 "How often do you tweet?" '15 times a month'
    -> "Do you only keep your twitter account\n for the rush you feel when your tweet is retweeted?"; 
 "How often do you tweet?" 'Almost everyday'
    -> "Are a majority of your tweets\n related to your business or industry?";

// css for states

state "Really?": {
  shape: octagon;
  background-color: black;
  text-color: white;
};

state "Maybe you should stick to Facebook": {
  shape: octagon;
  background-color: skyblue;
  text-color: white;
};


state "Get off Twitter": {
  shape: octagon;
  background-color: skyblue;
  text-color: white;
};


state "Get off Twitter and seek help": {
  shape: octagon;
  background-color: skyblue;
  text-color: white;
};

state "You can keep your Twitter account": {
  shape: octagon;
  background-color: skyblue;
  text-color: white;
};

state "Sorry Twitter just isn't for you": {
  shape: octagon;
  background-color: skyblue;
  text-color: white;
};

state "Does your boss follow you?" : {
  shape: octagon;
  background-color: yellow;
};

state Start : {
  background-color : limegreen;
  text-color       : white;
  shape            : octagon;
  linestyle        : dashed;
};
```

----

Thank you 😄

**Comment by boyter** [comment]
@StoneCypher Thanks for the excellent ticket. Ill get this prioritized and put in.

**Comment by StoneCypher** [comment]
Thank you sir

**Comment by StoneCypher** [comment]
I tried to reinstall from chocolatey but I got 3.0.0

I'll look into setting up a go stack tonight by which to test

Thank you for being so accommodating, responsive, and rapid
