### ISSUE TITLE
go install... command in README installs old version

### ISSUE THREAD

**Issue by c9845** [boyter/scc#353]
**Describe the bug**
The `go install github.com/boyter/scc@latest` noted in the repo README installs v2.12.0.  It looks like this should be `go install github.com/boyter/scc/v3@latest` instead (yay, pain in the next go modules!).

**To Reproduce**

1. Run `go install github.com/boyter/scc@latest`.
2. Run `scc --version`.  Version is output as v2.12.0.

**Expected behavior**
v3.1.0 (latest version as of this issue) being installed, which matches the documentation in the repo README.

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, and Linux (Ubuntu).
 - Version: all.

**Comment by boyter** [comment]
Fixed! Thanks for pointing it out.
