### ISSUE TITLE
Language support for INI configuration files

### ISSUE THREAD

**Issue by AnthonyMastrean** [boyter/scc#358]
Would be nice to see INI configuration file format support.

https://en.wikipedia.org/wiki/INI_file

**Comment by boyter** [comment]
What would your goal be here? What are you trying to achieve? Just config for the tool itself outside of doing it via the command line?

**Comment by AnthonyMastrean** [comment]
Oh, I'm sorry, I didn't say enough... I was referring to file type/format detection (sometimes you call that ["languages"](https://github.com/boyter/scc/blob/fff7a11827a2050975453ca7a68813e3c7185669/LANGUAGES.md)). For example, `scc` already detects TOML, JSON, and XML.

**Comment by boyter** [comment]
Ah! As a new language to recognize. Gotcha.

Done. Need to build from master, but will make it into the next release too.
