### ISSUE TITLE
Map several common file extensions to the MSBuild language

### ISSUE THREAD

**Issue by AnthonyMastrean** [boyter/scc#359]
Here are some project file extensions I'm encountering on a legacy codebase right now:

* [`vcproj`](https://fileinfo.com/extension/vcproj)
* [`vcxproj`](https://fileinfo.com/extension/vcxproj)
* [`vcxproj.filters`](https://fileinfo.com/extension/filters)

There are a handful of file extensions that are more Visual Studio than MSBuild, but MSBuild is still what's used under the hood to perform the actual compile/build.

* [`sln`](https://fileinfo.com/extension/sln)
* [`resx`](https://fileinfo.com/extension/resx)
* [`rdlc`](https://fileinfo.com/extension/rdlc)
* [`myapp`](https://fileinfo.com/extension/myapp)
* [`settings`](https://fileinfo.com/extension/settings)

**Comment by boyter** [comment]
@AnthonyMastrean if you want to do a PR to do this (and get the glory that this entails) you need only add the extensions here https://github.com/boyter/scc/blob/master/languages.json#L4134 and submit a PR. 

Otherwise I will do so in a few days and keep said fortune and glory for myself.

**Comment by boyter** [comment]
Shooting for glory!
