### ISSUE TITLE
chocolatey package

### ISSUE THREAD

**Issue by ThePhilderbeast** [boyter/scc#36]
in the same vein as the hombrew ticket, how about a package on chocolatey?

**Comment by ThePhilderbeast** [comment]
Ill take a look at it and see how i go

**Comment by boyter** [comment]
@ThePhilderbeast I added in a large chunk of whats required https://github.com/boyter/scc/tree/master/packages/chocolatey still need to work through the install and the like. 

Might require the creation of x86 builds though which ill put into a new release if required.

Something like the below would be the way to do this.

```
GOOS=windows GOARCH=386 go build -ldflags="-s -w" && zip -r9 scc-1.0.0-i386-pc-windows.zip scc.exe
```

**Comment by ThePhilderbeast** [comment]
I will take a look tonight when I get a chance

**Comment by boyter** [comment]
Closing because it would be better to put into the new Windows one.
