### ISSUE TITLE
Feature request: respect .gitignore etc at the topdir

### ISSUE THREAD

**Issue by laoshaw** [boyter/scc#361]
if I ran scc at the root of my git repo it works well, and much faster than cloc, tokei.

when I go to the sub directories, I found my python lines are in huge numbers, turns out the modules under .venv in this sub-directory is counted in though my .gitignore excludes it.

can scc check .gitignore etc as how git does?

**Comment by boyter** [comment]
Cheers. A reproducible test case always makes this easier.

**Comment by boyter** [comment]
OK this should now be resolved in current master branch due to the inclusion of proper .gitignore support.
