### ISSUE TITLE
fature request: raku language support

### ISSUE THREAD

**Issue by masukomi** [boyter/scc#362]
I'm noting that `cloc` has it but this doesn't. I'm writing a lot of raku these days and would prefer to use this :D

**Comment by boyter** [comment]
@masukomi would it be safe to copy the existing perl definitions for this? 

What extensions would we need?

**Comment by masukomi** [comment]
@boyter 
> would it be safe to copy the existing perl definitions for this?

no raku's a radically different language from Perl 5. It's just by the same people ;)  Honestly i'm surprised cloc has it. 

> What extensions would we need?

If you mean "file extensions" those would be `.raku`, `.rakumod`, `.rakutest`, `.rakudoc`, `.t`

`.t` and `.rakutest` are both test files containing raku.

`.rakudoc` is, i believe, expected to contain `pod6` (an evolution of Perl 5's `pod` documentation format. Note that it's different enough that the Perl5 pod parser's don't work on it) 

note:  The old `.p6` (or `.pl6`), `.pm6` (or `.pm` which is also supported, but discouraged) and .pod6 extensions will continue to be supported for 6.e and marked as deprecated in 6.f. We're currently at `v6.d` so we've got a while before those are officially deprecated. That being said, you're not going to find them in any new codebases so I'm not sure anyone would care.  


if you mean "extensions to scc" I don't know because i don't really understand where the language parsing instructions come from. I suspect, but don't actually know, that accurately calculating complexity for Raku functions might be a major pain in the butt given some of the language features. :/

**Comment by boyter** [comment]
So an example using perl (just since they are slightly related_ https://github.com/boyter/scc/blob/master/languages.json#L4981

What I need to know to add this is what extensions are in (and if duplicates, then how to keyword guess which is which) which is how it determines what the language is for processing. Im OK with adding deprecated ones since it processes older things too.

Ill see if I can find a language spec for raku when I get the chance, unless you know of one. That usually makes things much easier :)

**Comment by masukomi** [comment]
after looking at that json
ahh. gotcha. I think i can put that together. Raku doesn't have a Common Lisp level spec doc (massive tome) but i think what you want can be found here: https://docs.raku.org/

The [specification page](https://www.raku.org/specification/) is really more of a central place to find the latest test suites and links to design docs.

**Comment by boyter** [comment]
If you want to add it yourself let me know and you get the glory of the merged PR. Otherwise I will probably do it after christmas.

I suspect that the current #! check for perl might need to change, so that perl6 is picked up as Raku? Seems like it would make sense, but maybe Raku has its own #! check.

**Comment by masukomi** [comment]
I'm not playing in Perl these days but i suspect it's shebang will not be changing. 

raku would be `#!/usr/bin/env raku` or the path to wherever raku was installed.  It's best to pretend that there is absolutely no relation between Raku and Perl. Honestly the only meaningful connection between the two is that they're both managed by the [the perl foundation](https://www.perlfoundation.org/) and that the early Raku adopters were Perl geeks, but from a language perspective it's a totally different beast with a different VM.

I'm hoping to get to making you a PR, but just haven't yet... ;) Judging by the example json from perl it shouldn't be too hard, just... need to set aside the time to do it. Don't wait for me though. if you get a few moments and want to do it, i've got no problem with not having "the glory" ;)

**Comment by boyter** [comment]
Not in any rush, so happy to wait on this.

I only pointed at the perl example, as just an example :) If raku is the new #! then great that keeps everything as it was before.

No worries about time for PR, I am not in a rush for the next release yet.

**Comment by masukomi** [comment]
ok, starting to go through this. i have questions.

Why are there `!=` and `==` type check is the complexity stuff but not `<` or `>` type stuff?  why doesn't ruby have `do` or `each` or `times`  listed?

e.g.:
```
# 3 ways of writing the same thing 
10.times { |i| puts "hello #{i}" }
(1..10).each {|i| puts "helo #{i}"}
(1..10).each do |i| puts "helo #{i}"; end
```

**Comment by boyter** [comment]
No real reason, other then that's what I found at the time (or someone else did)

Feel free to add more of them as you see fit.
