### ISSUE TITLE
CSV-Stream doesn't CSV metacharacters in filenames

### ISSUE THREAD

**Issue by davidribyrne** [boyter/scc#371]
**Describe the bug**
The CSV-stream output is corrupted when the filename or location fields contain CSV metacharacters like commas. 

**To Reproduce**
What kind of monster would put commas in a filename? That's a great question:

```
wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.8.tar.xz
tar -xf linux-6.1.8.tar.xz
scc --format=csv-stream linux-6.1.8 | grep qcom,
```

**Expected behavior**
Double quotes in the location and filename fields should escaped by adding a second double quote and then each field should be surrounded with double quotes.

**Desktop (please complete the following information):**
 - OS: all
 - Version: 3.1.0 and earlier

**Comment by davidribyrne** [comment]
Submitted patch in pull request https://github.com/boyter/scc/pull/372/

**Comment by boyter** [comment]
Thanks so much for bug report and the PR! Merged in.
