### ISSUE TITLE
Python Library

### ISSUE THREAD

**Issue by ErnestFistozz** [boyter/scc#374]
Do you perhaps have a python library for `scc`?

**Comment by adam-moss** [comment]
I was wondering the same, but I ended up using the cli for what I wanted:

```python
scc_cmd = f"scc --format={scc_format} --sql-project={args.repo_path}"

sql = (
    subprocess.run(
        scc_cmd,
        cwd=temp_repo,
        shell=True,
        check=True,
        stdout=subprocess.PIPE,
    )
    .stdout.decode()
    .strip()
)
```

**Comment by ErnestFistozz** [comment]
@adam-moss , will try it out. I actually found [pytokei](https://pypi.org/project/pytokei/) which is a wrapper for [tokei](https://github.com/XAMPPRocky/tokei). Would be interesting to compare the output though. Thanks!

**Comment by boyter** [comment]
Yep the intention would be to use the JSON output for this purpose.
