### ISSUE TITLE
Can you please support GraphQL?

### ISSUE THREAD

**Issue by S-YOU** [boyter/scc#375]

**Comment by boyter** [comment]
Sure. Can you perhaps give some information to help with this?

**Comment by S-YOU** [comment]
Sure, thanks. Here is some information. 

```
extensions: graphql or graphqls

line_comment: #

doc comment: “”” … “”” (3 double quotes)

quotes: “ .. “ (double quotes)

blocks for complexity checks: type, input, query, mutation, subscription, directive, scalar, enum, interface, union, fragment

built-in types: Int, Float, String, Boolean, ID
```

Public graphql schema list can be find here:
https://github.com/IvanGoncharov/graphql-apis

GitHub graphql api v4: https://docs.github.com/en/graphql/overview/public-schema

**Comment by boyter** [comment]
28d05b352e25b35860df877091732a57812e198d

**Comment by S-YOU** [comment]
awesome, thanks!

**Comment by boyter** [comment]
You are welcome!
