### ISSUE TITLE
(incorrect?) Haskell keywords for complexity checks

### ISSUE THREAD

**Issue by 0rphee** [boyter/scc#384]
So, I checked the complexity checks for haskell code:
```haskell
 "Haskell": {
    "complexitychecks": [
      "for ", -- there are no for loops in haskell, there is a for function, nontheless, but it is not the same
      "for(", -- possibly this isn't needed, because parentheses aren't required
      "if ", -- there would be need to add also `then` 
      "if(", -- possibly this isn't needed, because parentheses aren't required
      "switch ", -- this keyword does not exist, instead it would be `case _expr_ of`
      "while ", -- there are no while loops in haskell
      "else ",
      "|| ",
      "&& ",
      "!= ", -- in haskell "not equals" is /=
      "== "
    ],
```
and I was a little surprised, since, those keywords seem to be kind of a "default" for many languages, though for haskell it is not the case. 

These are just some observations that quickly come to my mind, but here's a more comprehensive page of haskell keywords: https://wiki.haskell.org/Keywords

:)

**Comment by boyter** [comment]
I am not familiar with Haskell, so likely I made a mistake. Ill fix that for the next release. Cheers.

**Comment by fmease** [comment]
Same with Rust btw. (e.g. it should be `match` instead `switch`).

**Comment by boyter** [comment]
Now thats an odd one for me to miss.

**Comment by boyter** [comment]
5c34fee144364946374d78300215442a6ce059a1
