### ISSUE TITLE
In what unit, or how can I convert the complexity value

### ISSUE THREAD

**Issue by BuddhiLW** [boyter/scc#388]
I would like to know what I can compare the Complexity value to. For example, a project got 623 complexity (a very complex one), but how can I know if it's what I think, or what it actually is. 

Are there tables for projects, case studies, comparisons etc?

My output:
```
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
JavaScript                  18      8675      971       733     6971        623
```

How can I tell someone that this project is complex, you see what I mean? It's just a number, as it is.

**Comment by boyter** [comment]
Oddly enough I did do some work on this https://boyter.org/posts/an-informal-survey-of-10-million-github-bitbucket-gitlab-projects/ however I never folded the results back into this.

Something to put on my list.

I would suggest getting some other projects you know about and running against those to compare.

**Comment by BuddhiLW** [comment]
Thanks for the feedback
