### ISSUE TITLE
--exclude flag issues once you have >3, or after a directory exclusion

### ISSUE THREAD

**Issue by thirdwheel** [boyter/scc#40]
Seems that when you have more than three exclusions, it forgets the first three and starts over.

i.e. the output of:

    C:\Tools> scc X:\path\to\repo

is the same as

    C:\Tools> scc -e thing1-e thing2 -e thing3 -e nonexistent X:\path\to\repo

Similarly, the output of (assuming thing4 exists):

    C:\Tools> scc -e thing4 X:\path\to\repo

is the same as:

    C:\Tools> scc -e thing1-e thing2 -e thing3 -e thing4 X:\path\to\repo

Also, exceptions (both file and directory) after a directory exclusion seem to drop the directory exclusion - but reversing the order works if one of them is a file.

**Comment by boyter** [comment]
So exclude is a regex of which only the last one is counted.

`scc -e .`

would exclude everything when run whereas

 `scc -e . -e vendor`

would only exclude things matching vendor and the . would be ignored 

Assuming you wanted to exclude thing1, thing2 and thing3 you could do

`scc -e "thing1|thing2|thing3"`

Hope this clears it up.

**Comment by thirdwheel** [comment]
Clears it up nicely! You're a gentleman and a scholar. *tips hat*
