### ISSUE TITLE
Shields like style

### ISSUE THREAD

**Issue by hongbo-miao** [boyter/scc#402]
I am wondering is it possible to provide a shields-like style badge? Basically lowercase and blue. Thanks!

![image](https://github.com/boyter/scc/assets/3375461/0e800132-6eb5-4692-a7f9-e7f95bd204a2)

To compare, here is current style:

![image](https://github.com/boyter/scc/assets/3375461/f0e3b7e7-8ada-4fd4-9d80-d835f640482a)

BTW, thanks for this tool! 😃

**Comment by boyter** [comment]
Yep on the list. I need to redo the whole thing anyway as it costs more than I would like to pay.

**Comment by boyter** [comment]
OK https://github.com/boyter/scc/blob/master/cmd/badges/main.go you can find the code in there. Adding shields like support might be an idea just by having a param passed in, but regardless ill need to see about converting to the above.

Let me know if you are interested in adding this.

**Comment by boyter** [comment]
Great with the excellent work from @erjdev this is now possible. You can configure the look and feel using the below URL params,

```
font-color
font-shadow-color
top-shadow-accent-color
title-bg-color
badge-bg-color
```

EG the scc count with a horrible red font and blue background https://sloc.xyz/github/boyter/scc?font-color=ff0000&badge-bg-color=0000ff

**Comment by boyter** [comment]
Note still need to get the lowercase bit done, but ill look into that now.

**Comment by boyter** [comment]
Done. https://sloc.xyz/github/boyter/scc?font-color=ff0000&badge-bg-color=0000ff&lower=true

Now can set lower to lower the title.
