### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by assistcontrol** [boyter/scc#405]
Could you please cut a new release?

There have been many new languages added since 3.1.0 and as a downstream packager I'd love to be able to deploy them. Could we get a new release please?

Thanks for all the work you do. SCC is a great tool!

**Comment by boyter** [comment]
With Go 1.21 out I want to. I am just trying to finish the integration with https://github.com/boyter/gocodewalker/ to ensure that it has more accurate .ignore logic.

Alas I have not had the time to get around to it. It is on my todo pile though.

**Comment by boyter** [comment]
Done.
