### ISSUE TITLE
error in Ubuntu 18.06: file or directory does not exist 

### ISSUE THREAD

**Issue by lxyeternal** [boyter/scc#409]
```
(base) server@server-XX-7D32:/data1/codes/testdataset$ scc /data1/codes/
file or directory does not exist: /data1/codes
```
The test file is exist, but the scc can not to detect and report the error.

**Comment by boyter** [comment]
That's an odd one. Are you able to recreate it somehow?

**Comment by ErikPel** [comment]
Did you install with snap?

I ran into same issue and figured out that the snap version cannot run for files outside your home directory.

Try moving that folder to your /home/ and try again and check if that works

**Comment by boyter** [comment]
Ah yes... that sounds familiar. I should update that on the README

**Comment by boyter** [comment]
Confirmed it is included on the README.
