### ISSUE TITLE
Let badge exclude/include some folders

### ISSUE THREAD

**Issue by fzyzcjy** [boyter/scc#422]
Hi thanks for the project! I want to use it in https://github.com/fzyzcjy/flutter_rust_bridge, but the badge: https://sloc.xyz/github/fzyzcjy/flutter_rust_bridge/?category=lines does not reflect the real case - because I commit the generated code into the git repository as well (because this repo itself is a code generator).

Therefore, it would be great if there can be an option to exclude/include some folders when querying.

**Comment by boyter** [comment]
Probably the easiest way would be to commit a .ignore file which ignores the generated code. At least that's the easiest way that would work right now, and should help with a lot of other tools that support it.

Let me know if that works for you and solves your use case.

**Comment by fzyzcjy** [comment]
@boyter Thank you! It would be great if there could be a file named `.scc_ignore` or allow customize which ignore file path to use. Because I only want to exclude from line counting, but not from other tools.

**Comment by boyter** [comment]
Yep adding a .scc_ignore sounds like the best approach here then.

Although maybe `.sccignore` would be a better name... ill think on that.

**Comment by fzyzcjy** [comment]
Totally agree! Since `.gitignore` has no `_` as well

**Comment by boyter** [comment]
Added custom .ignore file support into the dependent library gocodewalker for this which unblocks this to be done.

**Comment by boyter** [comment]
OK done. 

This works if you build from master BUT because I yeeted the beta onto the badges server it will work there.

Add a new `.sccignore` file into your repository and it should be picked up. Standard .gitignore rules should apply but now they will only be applied by scc.

**Comment by fzyzcjy** [comment]
Looks great and thank you!

**Comment by boyter** [comment]
Great!
