### ISSUE TITLE
Feature Request Azure Bicep Support

### ISSUE THREAD

**Issue by Jeeppler** [boyter/scc#424]
## Issue

scc does not support [Azure Bicep](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview?tabs=bicep) at the moment. The support is missing from the `scc/language.json` file: https://github.com/boyter/scc/blob/master/languages.json

## Feature Request

Please add support for Azure Bicep.

**Comment by boyter** [comment]
Added in f41c082a4d01393b1a1dd5e5af55744be3d9cfe1

**Comment by Jeeppler** [comment]
@boyter awesome thank you 👍

**Comment by Jeeppler** [comment]
Are you planning to create a new release anytime soon?

**Comment by boyter** [comment]
Probably sometime after the next Go release to get the performance gains it usually brings.
