### ISSUE TITLE
RISCV assembly - can't count comments

### ISSUE THREAD

**Issue by rcordeau** [boyter/scc#429]
**Describe the bug**
Trying to compare against sloccount, and scc's ability to accurately count riscv assembly is off. It doesn't factor out comments (it can't see them)

**To Reproduce**
scc as a command
./scc asm_f.S

/****************************************************************************\
* This is a comment block
*
*
\****************************************************************************/

#include "thread_def.h"

.global ASM_ReturnToUserThread

**Expected behavior**
I expected an accurate count. of 2, but I got 7

Linux Ubuntu 22.04

**Comment by boyter** [comment]
Yeah, .s would be picked up as Assembly and according to the rules https://github.com/boyter/scc/blob/master/languages.json#L414 there is noting for multiline comments.
 
 Ill add it in now. You can get this if you build from source but with the new Go release ill be crafting a new build soon.

**Comment by boyter** [comment]
Build from source should resolve this. Otherwise give it a few days and ill push out a new release.
