### ISSUE TITLE
Incorrect calculation of the number of lines in a badge if it was added to the repository at the start

### ISSUE THREAD

**Issue by pomponchik** [boyter/scc#431]
Hello! 

I have added your experimental badge to several of my repositories. Several of them work fine, and several always display the same fixed number of lines: 18.

The badge works fine in these repositories:

- [instld](https://github.com/pomponchik/instld) - [![Lines of code](https://sloc.xyz/github/pomponchik/instld/?category=code)](https://github.com/boyter/scc/)
- [locklib](https://github.com/pomponchik/locklib) - [![Lines of code](https://sloc.xyz/github/pomponchik/locklib/?category=code)](https://github.com/boyter/scc/)
- [cantok](https://github.com/pomponchik/cantok) - [![Lines of code](https://sloc.xyz/github/pomponchik/cantok/?category=code)](https://github.com/boyter/scc/)

But! For these repositories, "18" is always displayed:

- [suby](https://github.com/pomponchik/suby) - [![Lines of code](https://sloc.xyz/github/pomponchik/suby/?category=code)](https://github.com/boyter/scc/)
- [full_match](https://github.com/pomponchik/full_match) - [![Lines of code](https://sloc.xyz/github/pomponchik/full_match/?category=code)](https://github.com/boyter/scc/)
- [sigmatch](https://github.com/pomponchik/sigmatch) - [![Lines of code](https://sloc.xyz/github/pomponchik/sigmatch/?category=code)](https://github.com/boyter/scc/)

I guess the difference is that in the second group of repositories, the badge was added at the start. I put the badge in the develop branch and they got into the main with the first PR.

**Comment by boyter** [comment]
Its usually a case of github caching it. If you look at the actual rendered link it goes though githubs servers first.

For example https://camo.githubusercontent.com/b19935ed836c142d0eb7b654cc2045c600b5cfd273f316f16760af3511b722d0/68747470733a2f2f736c6f632e78797a2f6769746875622f706f6d706f6e6368696b2f7369676d617463682f3f63617465676f72793d636f6465 is the link for sigmatch from the above.

I don't actually know how to bust this cache myself....

While the badge server does cache as well its not as aggressive as the github one.

**Comment by pomponchik** [comment]
- [sigmatch](https://github.com/pomponchik/sigmatch) - [![Lines of code](https://sloc.xyz/github/pomponchik/sigmatch/?category=code?)](https://github.com/boyter/scc/)

**Comment by pomponchik** [comment]
I found the answer!

Look: 
- [sigmatch](https://github.com/pomponchik/sigmatch) - [![Lines of code](https://sloc.xyz/github/pomponchik/sigmatch/?category=code?)](https://github.com/boyter/scc/)

You need [only a question sign](https://stackoverflow.com/a/66030456/14522393).

**Comment by boyter** [comment]
I think that will only bust the cache once though. Of course you can always add more at the end to rebust it.

Ill have a look through that thread because there might be some other solutions raised.

**Comment by boyter** [comment]
Should be resolved now.
