### ISSUE TITLE
[question] how to show Files column in csv format

### ISSUE THREAD

**Issue by marslo** [boyter/scc#433]
**Describe the bug**
The `Files` column ( count of files ) shows in tabular/json format, but doesn't shows in csv format, details as below:

![image](https://github.com/boyter/scc/assets/5822057/62e647aa-37bb-4c0a-8ed1-ecadf5f26abe)

**To Reproduce**
1. how you were using `scc` either as command line or library:
   `command line`
2. If command line please list the arguments. If library please supply code to demonstrate the issue.
   ```bash
   # csv
   $ scc --include-ext c,ec,pgc,h,cc,cpp,cxx,c++,pcc,in,hh,hpp,hxx,inl,ipp --no-cocomo --no-size --no-duplicates --format=csv <folder_1> <folder_2> > file.csv

   # tabular
   $ scc --include-ext c,ec,pgc,h,cc,cpp,cxx,c++,pcc,in,hh,hpp,hxx,inl,ipp --no-cocomo --no-size --no-duplicates <folder_1> <folder_2>

   # json
   $ scc --include-ext c,ec,pgc,h,cc,cpp,cxx,c++,pcc,in,hh,hpp,hxx,inl,ipp --no-cocomo --no-size --no-duplicates --format=json <folder_1> <folder_2> > file.json
   ```

**Expected behavior**
Has `Files` column in csv format, or any params to turn on/off Files column

**Desktop (please complete the following information):**
 - OS: Linux + WSL:
   ```bash
   # Linux( Ubuntu 22.04 )
   $ uname -a
   Linux HOSTNAME 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

   # wsl ( Ubuntu 22.04 )
   $ uname -a
   Linux HOSTNAME 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
   ```
 - Version:
   - Linux ( Ubuntu 22.04 ): `scc version 3.2.0`
   - WSL ( Ubuntu 22.04 ): `scc version 3.1.0`

**Comment by boyter** [comment]
This was intentional when I created the csv format, because the underlying idea was that it would be used to create your own aggregations (similar to the SQL output format). As such I kept it as simple as possible because adding calculated columns makes parsing it after a little more annoying.

Whats the use case here? Im not opposed to making changes, but I would really want to know what you are trying to achieve.

**Comment by marslo** [comment]
Hey @boyter,

I've using `scc` to collect data and generate slides, and since csv can be recognized by Excel, so it's easy to transfer to chart ( as below ).
<img width="993" alt="csv-ppt-chart" src="https://github.com/boyter/scc/assets/5822057/2d1841a3-e9cf-4580-a71c-d9e5cd64758f">


So, if the columns can be configurable via parameters, it will be awesome.
thanks

**Comment by boyter** [comment]
Yep I promise the moment I am not swamped at work I will be getting back to doing a lot of these things.

Main goal will be to improve the gitfile support, followed by all of these sort of changes. I have not forgotten, just no time right now.

**Comment by boyter** [comment]
Done.

```
$ scc -f csv -u ./processor
Language,Lines,Code,Comments,Blanks,Complexity,Bytes,Files,ULOC
Go,8136,6402,410,1324,1400,369653,23,3293
```

Files as a count is in the summary now, along with the new special ULOC calculation (if you want it). Will make it into the next release, which should be done in a week or so.

**Comment by marslo** [comment]
nice thanks. verified !
