### ISSUE TITLE
Premature entry evicting in HashCache

### ISSUE THREAD

**Issue by feymartynov** [boyter/scc#436]
The following example often panics proving that HashCache may evict entries even when capacity is not yet fully occupated.

```rust
const CAPACITY: usize = 64;
let hc = scc::HashCache::with_capacity(CAPACITY, CAPACITY);

for i in 0..CAPACITY {
    let k = format!("key{i}");

    match hc.put(k, i).unwrap() {
        None => (),
        Some((k, _)) => panic!("Evicted {k}"),
    }
}
```

Is this a bug or normal behavior?
If it's normal, I think it should be documented.

**Comment by boyter** [comment]
Are you sure you are in the right project?

**Comment by feymartynov** [comment]
Sorry, that's wrong one :)
