### ISSUE TITLE
Add support for MDX file extension

### ISSUE THREAD

**Issue by NathanielHill** [boyter/scc#439]
Sorry, do not have time to contribute, but wanted to add this in case it adds any value as a backlog item.

Feel free to close, will not be offended.

MDX has been around for a few years and is frequently used in frontend sites for text heavy content like blog posts.

https://mdxjs.com/docs/what-is-mdx/

**Comment by boyter** [comment]
Ill have a play around later to adding this.

**Comment by sgoggins** [comment]
@boyter : The syntax in these files appears to be quite similar to, if not entirely, the syntax dynamics of markdown. This might be a quick add. Here's a whole directory of files like this for quick reference: https://github.com/hashicorp/terraform/tree/main/website/docs

**Comment by boyter** [comment]
Neat. Merged in. Thanks so much for adding it.
