### ISSUE TITLE
"Text" rather than "Plain Text"?

### ISSUE THREAD

**Issue by leoheitmannruiz** [boyter/scc#444]
Hey :)

Minor question:
What do you think about reporting non-language files as "Text" rather than "Plain Text"?

To me, plain text seems like a format, as in, not binary.

Files recognized as Go or whatever language else are plain text as well, right?

**Comment by boyter** [comment]
I think I copied that from Visual Studio Code which says plain text. At least thats what my memory suggests.

![CleanShot 2024-03-28 at 09 28 51@2x](https://github.com/boyter/scc/assets/612151/a293ac8b-a511-4601-95a3-43c4763a1136)
