### ISSUE TITLE
Could you please release a new version?

### ISSUE THREAD

**Issue by askzy** [boyter/scc#450]
**Describe the bug**
Latest scc release cannot handle graphql files

**To Reproduce**
`brew install scc` gets 3.2.0, which includes commits up to 2023 Nov, not including graphql.
`go install github.com/boyter/scc/v3@latest` gets 3.2.0
`go install github.com/boyter/scc@master` gets 3.0.0, not latest master

**Expected behavior**
I thought `go install github.com/boyter/scc@master` would get latest commits on master branch here but it doesn't :(
I ended up downloading the code and `go build` it to get 3.3.0 beta.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.4.1

so.. maybe time to release 3.3.0 containing the fixes since last December?

**Comment by boyter** [comment]
It really is on my list, just need to get the time to bring in the git improvements that I have wanted to go in for a while now. The moment I am not slammed with paying work its something I will be doing.

**Comment by boyter** [comment]
Good news. The git support I wanted has been merged in so a release is close.

**Comment by askzy** [comment]
Thank you! 🙏
