### ISSUE TITLE
Error in 'm'ain.ts' File Prevents Installation in Go

### ISSUE THREAD

**Issue by AdrianKoszalka** [boyter/scc#453]
**Describe the bug**
When attempting to install the newest version (v3.3.2) of scc via Go, an error occurs due to a malformed file path in the `m'ain.ts` file.

**To Reproduce**

1. Execute the following install command:
`go install github.com/boyter/scc/v3@latest`
2. An installation error occurs:
`go: github.com/boyter/scc/v3@latest: create zip: examples/issue333/m'ain.ts: malformed file path "examples/issue333/m'ain.ts": invalid char '\''`

**Expected behavior**
The installation should be successful without any errors.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 3.3.2

**Comment by boyter** [comment]
Urgh. Thats very annoying because that's a legitimate filename. 

I have removed the file so this should not work, but this is an issue in Go itself or some dependency it has.
