### ISSUE TITLE
Recommended install method fails due to malformed file name

### ISSUE THREAD

**Issue by tahyonline** [boyter/scc#454]
**Describe the bug**
Using the recommended installation method, the download fails due to a file name in repo.

**To Reproduce**

```
$ go install github.com/boyter/scc/v3@latest
go: downloading github.com/boyter/scc/v3 v3.3.2
go: github.com/boyter/scc/v3@latest: create zip: examples/issue333/m'ain.ts: malformed file path "examples/issue333/m'ain.ts": invalid char '\''
```

**Expected behavior**

Installation should work just like for v3.2.0, `go install github.com/boyter/scc/v3@v3.2.0` does not produce the error, but all versions of v3.3.x do.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version 14.4.1 (23E224)
 - Go: go version go1.22.2 darwin/arm64

**Comment by redblade7** [comment]
I have the same problem on Gentoo Linux, same go version as OP.

**Comment by boyter** [comment]
Annoying. I thought by removing it in the main branch it would resolve it.

I may have to cut a new release to get around this. Ill add some new languages to make it worthwhile to assist with it.

**Comment by boyter** [comment]
K the new release just pushed out then with additional language support should resolve this for everyone.

**Comment by tahyonline** [comment]
Worked, thanks!

**Comment by boyter** [comment]
Great. Also handy tip, don't create files with a ' in the filename.
