### ISSUE TITLE
Use scc as library

### ISSUE THREAD

**Issue by lafriks** [boyter/scc#48]
It would be great if code could be updated to be able to use it as a library

**Comment by boyter** [comment]
Oh that would be very neat. Let me know if there is anything you need documentation wise or implementation side to assist with that and ill sort it out.

**Comment by boyter** [comment]
@lafriks Any issues with this? Anything I can do to assist?

**Comment by lafriks** [comment]
Sorry was a bit busy, I think issue can be closed, will comment here if I have problems or updates

**Comment by boyter** [comment]
No problem.
