### ISSUE TITLE
Feature: add support for shebang for R

### ISSUE THREAD

**Issue by alexaandru** [boyter/scc#490]
R language also has support for shebang, via `Rscript`: https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/Rscript

**Comment by apocelipes** [comment]
Hi, I'm trying to add the Rscript shebang support. You can find a simple Rscript example in "examples/language/rscript.r".

**Comment by alexaandru** [comment]
Awesome! Yes, that example looks good!
