### ISSUE TITLE
BUG: Panicking on "concurrent map read and map write"

### ISSUE THREAD

**Issue by apocelipes** [boyter/scc#498]
I ran the "test-all.sh" then I got a fatal error:
![image](https://github.com/user-attachments/assets/609f5a2f-da80-4358-a53e-06bb5a0b9582)

This error was introduced by 82225f8, the function "aggregateLanguageSummary" and "processFile" accessed the map at the same time.

Use the ulocMutex in "aggregateLanguageSummary" can fix this panic.

**Comment by apocelipes** [comment]
> Odd... as there should be no race condition possible inside the aggregation as it is single threaded, and I do run the race detector over this, as well as run scc 10's of thousands of times to ensure everything is as expected.

aggregateLanguageSummary loops over the input chan to collect the data(include the data from ulocLanguageCount), while processFile is writing data to the chan in another goroutine. aggregateLanguageSummary reads the map ulocLanguageCount and processFile writes data to it. Other aggregation functions do not have this problem because they are accessing the map after looping over the input chan, that means processFile is done and no any other goroutines can access ulocLanguageCount at the same time. The probability of this data race is low but it still happens several times on my environment.

**Another way to fix this race is that recording the uloc-key then we can get data from ulocLanguageCount after the ending of the loop. This is handled in the same way as other aggregation functions and does not require locks. This makes the code a bit more complex and consumes a bit more memory. But I think the costs are worth it and the performance will be better than the locking solution.**

> Are you calling scc as a library function or something?

I only ran the test-all.sh on my linux virtual machine.

**Comment by apocelipes** [comment]
@boyter 
I'd like to change to the no-locking solution, if the code is too complex we can just use the lock to prevent racing.

**Comment by boyter** [comment]
Ah yes. I had forgotten all the different nuances of the formatters. Its not something I have to change very often. Something I should consider rewriting at some point.

Anyway yes the no-locking solution is much better for this. Merged and will make it into the next release. Thanks so much for finding it, because as alluded to I have not managed to replicate locally.
