### ISSUE TITLE
Bug: astro files cannot be counted 

### ISSUE THREAD

**Issue by TerrniT** [boyter/scc#511]
**Describe the bug**
Astro files cannot be counted 

**To Reproduce**

1. Use scc in astro js repo

**Expected behavior**
astro files should be counted in the result table 

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Ubuntu 22.04

**Comment by boyter** [comment]
Can you supply some examples, and ideally the link to the astro documentation? I will then be happy to add it in.

**Comment by apocelipes** [comment]
@boyter 
A simple specfication can be found here <https://docs.astro.build/en/basics/astro-syntax/> and here <https://docs.astro.build/en/basics/astro-components/#component-structure>.
Basically, the syntax is similar to Vue components.

**Comment by boyter** [comment]
Sitting in master branch and will make it into the next release.
