### ISSUE TITLE
Ignore files in gitignore

### ISSUE THREAD

**Issue by mbkv** [boyter/scc#53]
This might be the against the purpose of this project, but personally I've been too spoiled from ag

When I was using it to measure a few of my projects, it spent an awfully long time working in node_modules and dist, when I just wanted to see the results of my TypeScript. So hiding gitignore files will make the results more accurate in this case

On the other hand, it is interesting to see the cumulative amount of work done in an open source project. So maybe it should just be a flag

**Comment by boyter** [comment]
Sorry about the late response, I was taking a much needed break over the last week!

This is actually something I need to look at more closely. I even wrote this comment https://github.com/boyter/scc/blob/master/processor/file.go#L76 `TODO the gitignore should check for further gitignores deeper in the tree` although I suspect that it may not be working at all.

Things to do. Determine if the used import github.com/monochromegane/go-gitignore is good enough as a git-ignore parser. Then either continue using it or find a replacement (I really do not want to write my own!)

Then work on the logic to have this work properly.

For the moment you can supply the argument `--exclude-dir` like so `scc --exclude-dir node_modules,.git .`  which will then ignore the root node_modules and .git directories. Or if you have nested ones you can use `-M` like so `scc -M node_modules .` which will exclude nested ones.

**Comment by boyter** [comment]
So the latest release should now obey the .gitignore in the root of the directory correctly. I am yet to make it apply recursively but it should now be possible. 

I still need to add an option to disable it though, but I belive by default it should be on. I tried using it on a codebase I have with a lot of ignores and it produces better results closer to what I would expect so I would say its a good thing to have.

**Comment by boyter** [comment]
Please note, that .ignore files are now also working for the few tests I tried. These apply similar to how `rg` and `ag` use them. I belive tokei also follows them.

**Comment by boyter** [comment]
Added just then to master new options.

`--ignore` when set will disable .ignore file logic
`--gitignore` when set will disable .gitignore file logic

That should be enough flexibility. Still need to improve the gitignore logic itself but this is MUCH better than before.

**Comment by dbaggerman** [comment]
Having an `--ignore` flag to _not_ ignore things seems back to front to me.

Changing these to `--no-ignore` and `--no-gitignore` would probably be more intuitive.

**Comment by boyter** [comment]
Thats what I get for getting toasted and writing code, I forgot PR to check that stuff, changed.

**Comment by boyter** [comment]
This has been implemented and released.
