### ISSUE TITLE
Add installation instructions to README

### ISSUE THREAD

**Issue by sixhobbits** [boyter/scc#56]
I would make a PR but I'm a Go noob and not actually sure of best practice.

This is a great tool, but it took me a really long time to work out how to get it running. 

Would it be possible to add instructions to install to the README file, or at least link to https://github.com/boyter/scc/releases somewhere.

**Comment by boyter** [comment]
Done.

https://github.com/boyter/scc#install

Let me know if you think that is sufficient and we can close this down.

**Comment by sixhobbits** [comment]
Thanks so much! Great :) 

Looking forward to seeing progress on this one too. https://github.com/boyter/scc/issues/19

**Comment by boyter** [comment]
Excellent. Yes thats something id really like some help with seeing as I don't have a Mac to test it out on.
