### ISSUE TITLE
Python docstrings are counted as code

### ISSUE THREAD

**Issue by olivren** [boyter/scc#62]
I tried scc 2.2.0 on Windows, on a python file, and it appears that Python docstrings are counted as code instead of comments.

```python
'''This is a module docstring'''

class C:
  '''
  This is a class docstring
  '''
  
  def f():
    """This is a function docstring.
    simple quotes and double quotes are equivalent
    """
    pass
```

lines: 12
code: 10
comments: 0
blanks: 2

This should be:
lines: 12
code: 3
comments: 7
blanks:2

**Comment by boyter** [comment]
So the reason `scc` and the other tools do this is due to Python using triple quotes as strings.

```
>>> '''this is string'''.split()
['this', 'is', 'string']
```

Knowing the difference between a docstring or a string in the file I don't think is possible without parsing the code using an AST which is going to be incredibly slow compared to how all of the tools currently work. 

I am not sure how python treats them in the interpreter but I belive it actually processes them every run which would mean that according to Python they are lines of code as well.

I belive this was raised enough with tokei which produced the `treat_doc_strings_as_comments = true` setting in its toml config to stem the issue requests. Not sure if I agree with this approach myself.

If you can think of a way to reliably identify when it is a doc string vs an actual string, perhaps with some test cases I would be happy to implement this though. Some thoughts I have to help with this.

```If the triple quote string starts following a newline with only white-space characters in front and ends followed by only a newline or white-space characters it is a comment```

Not sure if that is exclusive enough to catch all cases though.

**Comment by olivren** [comment]
The method you describe is indeed the best heuristic I can think of. If you want to be be even more strict, you can also add a contition that the previous line does not end with `\`, which indicates a line continuation. That would prevent this snippet to be considered a docstring.

```python
message = \
"""
hello
world
"""
```

Here is how I would rank the various strategies, from the worst to the best:
1. Interpret all the triple quoted strings as code (current behavior)
2. Interpret all the triple quoted strings as comments
3. Your proposed heuristic
4. Your proposed heuristic with the additional handling of line continuation

Of course it's possible to use a real parser, but it needs to work with various versions of Python, and be resilient to malformed code. It would probably need one of these heuristics as a fallback, anyway.

**Comment by boyter** [comment]
I am not a huge fan of option 2 personally. I would rather implement this properly. I just need to figure out how to change the JSON language structure to support this and I will start looking at implementing.

**Comment by boyter** [comment]
Attempting to implement on this branch https://github.com/boyter/scc/tree/issue62

**Comment by boyter** [comment]
Since this is related to #71 I am implementing a more generic solution there and discarding the work on the branch. I will remove it eventually once I have things working.

**Comment by boyter** [comment]
The JSON changes needed to support this are sitting here https://github.com/boyter/scc/pull/76

Once all 3 pending PR's are merged in I will resume work on this issue.

**Comment by boyter** [comment]
Merged in, should be all good now.

**Comment by Freed-Wu** [comment]
Some docstring starts with `r""""`:

```python
r'''This is a module docstring'''

class C:
  r'''
  This is a class docstring
  '''

  def f():
    r"""This is a function docstring.
    simple quotes and double quotes are equivalent
    """
    pass
```

Can we support this situation?

cc: @lukas-brenning

PS: https://github.com/XAMPPRocky/tokei/discussions/1362

**Comment by boyter** [comment]
Pretty sure that should be handled.

Adding this test case,

```
func TestCountStatsPythonRawDocstring(t *testing.T) {
	ProcessConstants()

	content := `r'''This is a module docstring'''

class C:
  r'''
  This is a class docstring
  '''

  def f():
    r"""This is a function docstring.
    simple quotes and double quotes are equivalent
    """
    pass
`

	fileJob := FileJob{Language: "Python"}
	fileJob.SetContent(content)
	CountStats(&fileJob)

	if fileJob.Comment != 7 {
		t.Errorf("Expected 7 comment lines (docstrings) got %d", fileJob.Comment)
	}
	if fileJob.Code != 3 {
		t.Errorf("Expected 3 code lines got %d", fileJob.Code)
	}
	if fileJob.Blank != 2 {
		t.Errorf("Expected 2 blank lines got %d", fileJob.Blank)
	}

	plain := strings.ReplaceAll(content, "r'''", "'''")
	plain = strings.ReplaceAll(plain, "r\"\"\"", "\"\"\"")

	plainJob := FileJob{Language: "Python"}
	plainJob.SetContent(plain)
	CountStats(&plainJob)

	if plainJob.Comment != fileJob.Comment || plainJob.Code != fileJob.Code || plainJob.Blank != fileJob.Blank {
		t.Errorf("Raw docstring counts (c=%d code=%d b=%d) differ from plain (c=%d code=%d b=%d)",
			fileJob.Comment, fileJob.Code, fileJob.Blank,
			plainJob.Comment, plainJob.Code, plainJob.Blank)
	}
}
```

shows that it does. Going to commit that now just to ensure its locked in.

**Comment by Freed-Wu** [comment]
```sh
$ scc --version
scc version 3.7.0
$ cat a.py
r'''This is a module docstring'''

class C:
  r'''
  This is a class docstring
  '''

  def f():
    r"""This is a function docstring.
    simple quotes and double quotes are equivalent
    """
    pass
$ scc
───────────────────────────────────────────────────────────────────────────────
Language            Files       Lines    Blanks  Comments       Code Complexity
───────────────────────────────────────────────────────────────────────────────
Python                  1          12         0         3          9          0
───────────────────────────────────────────────────────────────────────────────
Total                   1          12         0         3          9          0
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop (organic) $192
Estimated Schedule Effort (organic) 0.53 months
Estimated People Required (organic) 0.03
───────────────────────────────────────────────────────────────────────────────
Processed 203 bytes, 0.000 megabytes (SI)
───────────────────────────────────────────────────────────────────────────────
# Expected:
───────────────────────────────────────────────────────────────────────────────
Language            Files       Lines    Blanks  Comments       Code Complexity
───────────────────────────────────────────────────────────────────────────────
Python                  1          12         0         7          5          0
```
