### ISSUE TITLE
runtime: failed to create new OS thread (have 2049 already; errno=12) fatal error: runtime.newosproc

### ISSUE THREAD

**Issue by psalvitti** [boyter/scc#7]
macOS: Sierra (10.12.6)

Get this error trying to `scc` one of our (large) Java application directories. Using verbose mode indicates 1025 `WARN`-ings prior to the runtime failure. Command line:

`~/code/scc -v .` (no other options)

stack trace attached: 
[scc-stack.txt](https://github.com/boyter/scc/files/2073095/scc-stack.txt)

**Comment by boyter** [comment]
Going to make a guess that this is a ulimit issue. Seems to happen more on macOS than anything else. 

Would it be possible for you to try setting it using the following links to something much higher than the default?

https://superuser.com/questions/261023/how-to-change-default-ulimit-values-in-mac-os-x-10-6#306555
https://unix.stackexchange.com/questions/108174/how-to-persistently-control-maximum-system-resource-consumption-on-mac/221988#221988

If it is still broken then I will need to see if I can borrow another Mac and try to replicate.

**Comment by psalvitti** [comment]
Yes, I'll give that a try and report back with findings.

**Comment by psalvitti** [comment]
macOS `ulimit` issue related.

**Comment by boyter** [comment]
No problem at all. Glad it was that issue. Might need to add some better reporting around it.
