### ISSUE TITLE
Panic When Using Glob

### ISSUE THREAD

**Issue by nsmryan** [boyter/scc#77]
I got a panic when running scc on the command line in Windows 10.

The command was:
```shell
scc */*.cpp 
```
when run on a directory with no sub-directories (I forgot which directory I was in and ran this by accident). The same command works fine when there are sub-directories to enter.

The error message was:
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x52ad92]

goroutine 4 [running]:
github.com/boyter/scc/processor.walkDirectoryParallel(0x1140a080, 0x7, 0x11482140)
        /home/bboyter/Go/src/github.com/boyter/scc/processor/file.go:84 +0xf2
github.com/boyter/scc/processor.Process.func1.1(0x1140a080, 0x7, 0x11482140, 0x1140a070)
        /home/bboyter/Go/src/github.com/boyter/scc/processor/processor.go:344 +0x31
created by github.com/boyter/scc/processor.Process.func1
        /home/bboyter/Go/src/github.com/boyter/scc/processor/processor.go:343 +0xa5
```

Not a big issue, since the glob doesn't match any files anyway, but an error message would be nicer than a panic.

**Comment by boyter** [comment]
Fix sitting in PR https://github.com/boyter/scc/pull/78 which I will merge once it ensures the build works as expected.

Thanks for reporting this. I could only trigger it on Windows but it is now resolved,

```
C:\Users\bboyter\Documents\Go\src\github.com\boyter\scc>go run main.go */*.cpp
ERROR 2019-05-06T22:18:07Z: GetFileAttributesEx *\*.cpp: The filename, directory name, or volume label syntax is incorrect.exit status 1
```

**Comment by boyter** [comment]
Merged into master. Will be rolled into the next release. If you need a fix now then please build from master.

Once again thanks for reporting this!
