### ISSUE TITLE
zsh: command not found: scc

### ISSUE THREAD

**Issue by seanmars** [boyter/scc#86]
Install by `go get -u github.com/boyter/scc/`.

But output `zsh: command not found: scc` when use `scc`

**Desktop (please complete the following information):**
 - OS: Windows WSL ubuntu

**Comment by dbaggerman** [comment]
Hi @seanmars,

If you're not familiar with golang, you might find it easier to get scc from the releases page: https://github.com/boyter/scc/releases/tag/v2.5.0

If you would like to compile it yourself, `go get` only downloads the source code. You will need to run `go install github.com/boyter/scc` to compile and install. Go installs to `$GOPATH/bin`, and you may need to add this to your `$PATH` before `zsh` will find it.

**Comment by boyter** [comment]
Hi @seanmars 

Pretty much what @dbaggerman said above. You appear to have Go setup, so thats a good start. Here is what I include in my .zshrc file to allow building like the above,

```
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/Go
export PATH=$PATH:$(go env GOPATH)/bin
```

I suspect you are missing the last part if you have already run `go install` for it. Keep in mind you can always copy into the `/usr/bin` directory if you like.

**Comment by boyter** [comment]
No response in 6 days. Going to assume it was resolved and close it down.
