### ISSUE TITLE
Add minified/generated file check

### ISSUE THREAD

**Issue by boyter** [boyter/scc#92]
Similar to binary, if the file appears to be minified or generated perhaps don't include it.

**Comment by boyter** [comment]
@dbaggerman Would love some thoughts on the below.

There are a few things to consider here. The first being should be be included by default IE minified files are excluded. I can see this being correct because like .git folders you probably don't want to include them but also wrong because it was committed, and as such is part of the codebase. I am slightly leaning towards it being a flag to opt into.

The second thing is should the files be excluded, or perhaps counted in a different bucket (or optionally both). For example if I have JavaScript and turn the functionality on the result may look like 

```
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
JavaScript                  29     13485     2640      2541     8304       1733
(min) JavaScript         29     13485     2640      2541     8304       1733
───────────────────────────────────────────────────────────────────────────────
```

I have prefixed the (min) because for large languages it would otherwise be cut off. Although this makes sorting a bit of a pain... or win as all the minified types would be lumped together.

Being able to exclude the minified files would also be an option but I like the above due to it still counting, just as a different name.

This would work for JavaScript, JSON, XML, CSS and a bunch of other file types.

**Comment by boyter** [comment]
Ideas on how to implement this.

https://twitter.com/schristopheraz/status/1182247287835234304?s=20

```
Line length of line 1 > 50
If file fileName[1]= "min"
If spaces.count() < 10 (lol)
If carriage return count < 3
```

Might work. However I think 50 is too low, 300 might be a better number to avoid false positives.

**Comment by jhaynie** [comment]
we did a lot of testing based on our data set and came up with these numbers. not perfect per se. we'll probably revisit at some point to build a more accurate model but this seems to work well for us: https://github.com/pinpt/ripsrc/blob/master/ripsrc/fileinfo/fileinfo.go#L44

**Comment by boyter** [comment]
I did consider a hard cut byte size as well. Might expand the ticket out to cover "generated" files which that would do. Cheers.

**Comment by boyter** [comment]
Trying out on https://github.com/boyter/scc/tree/minified

Seems a very simple check works quite well for all my test cases so far.

**Comment by boyter** [comment]
Picks up the `constants.go` file in this repository which is pretty neat.
