### ISSUE TITLE
Add support for WSDL files

### ISSUE THREAD

**Issue by cardil** [boyter/scc#95]
Scc should support WSDL files. They might be treated as an XSLT files or as separate type.

**Comment by boyter** [comment]
Done. Based it on XML files since last time I checked WSDL was just XML. Build from master to get the support.

**Comment by cardil** [comment]
Same for XSD and XSLT - there are also XML. But they have they separate type. Why not add a dedicated type for this as well?

**Comment by boyter** [comment]
I did add a dedicated type. Its just based on XML rules is all.
